import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { applyFix } from "@/analysis/fixes";
import type { Control, Finding, Project, Remediation } from "@/core/types";
import { buildDeveloperHandoff } from "./handoff";

export interface PullRequestResult {
  branch: string;
  title: string;
  body: string;
  committed: boolean;
  prUrl: string | null;
  message: string;
}

function runGit(rootPath: string, args: string[]): string {
  return execFileSync("git", ["-C", rootPath, ...args], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  }).trim();
}

function isGitRepo(rootPath: string): boolean {
  try {
    runGit(rootPath, ["rev-parse", "--is-inside-work-tree"]);
    return true;
  } catch {
    return false;
  }
}

function ghAvailable(): boolean {
  try {
    execFileSync("gh", ["--version"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    return true;
  } catch {
    return false;
  }
}

/**
 * Applies the finding's fix on a new branch, commits, and optionally opens a
 * GitHub PR via `gh` when authenticated. Falls back to branch+commit only.
 */
export function preparePullRequest(
  project: Project,
  control: Control,
  finding: Finding,
  remediation: Remediation,
): PullRequestResult {
  if (!isGitRepo(project.rootPath)) {
    throw new Error(
      "Pull request preparation requires a git repository at the project root.",
    );
  }
  if (!finding.fix) {
    throw new Error("This finding has no automatable fix to commit.");
  }

  const handoff = buildDeveloperHandoff(project, control, finding, remediation);
  const shortId = finding.id.slice(0, 8);
  const branch = `complyloop/fix-${finding.checkId}-${shortId}`;

  const currentBranch = runGit(project.rootPath, ["rev-parse", "--abbrev-ref", "HEAD"]);
  const absolute = path.join(project.rootPath, finding.location.filePath);
  const original = fs.readFileSync(absolute, "utf8");
  const fixed = applyFix(original, finding.fix);

  try {
    runGit(project.rootPath, ["checkout", "-b", branch]);
    fs.writeFileSync(absolute, fixed);
    runGit(project.rootPath, ["add", "--", finding.location.filePath]);
    runGit(project.rootPath, [
      "commit",
      "-m",
      handoff.title,
      "-m",
      "Generated by ComplyLoop. Verify with the automated check before merge.",
    ]);
  } catch (error) {
    // Best-effort restore to the previous branch if branch creation/commit failed mid-way.
    try {
      runGit(project.rootPath, ["checkout", currentBranch]);
    } catch {
      /* ignore */
    }
    throw error;
  }

  let prUrl: string | null = null;
  let message = `Branch \`${branch}\` created with the fix committed. Push and open a PR, or install/authenticate \`gh\` for automatic PR creation.`;

  if (ghAvailable()) {
    try {
      runGit(project.rootPath, ["push", "-u", "origin", "HEAD"]);
      prUrl = execFileSync(
        "gh",
        [
          "pr",
          "create",
          "--title",
          handoff.title,
          "--body",
          handoff.body,
          "--head",
          branch,
        ],
        {
          cwd: project.rootPath,
          encoding: "utf8",
          stdio: ["ignore", "pipe", "pipe"],
        },
      ).trim();
      message = `Pull request created: ${prUrl}`;
    } catch {
      message = `Branch \`${branch}\` committed locally. Push failed or \`gh pr create\` is unavailable — use the developer handoff patch/body.`;
    }
  }

  return {
    branch,
    title: handoff.title,
    body: handoff.body,
    committed: true,
    prUrl,
    message,
  };
}
