import fs from "node:fs";
import path from "node:path";
import simpleGit from "simple-git";
import { applyFix } from "@/analysis/fixes";
import type { Control, Finding, Project, Remediation } from "@/core/types";
import { githubCloneUrl } from "./connect";
import { getStoredGitHubToken } from "./github-tokens";
import { buildDeveloperHandoff } from "./handoff";
import { createOctokit, octokitErrorMessage } from "./octokit";

export interface PullRequestResult {
  branch: string;
  title: string;
  body: string;
  committed: boolean;
  prUrl: string | null;
  message: string;
}

async function createPullRequestViaApi(options: {
  fullName: string;
  accessToken: string;
  head: string;
  base: string;
  title: string;
  body: string;
}): Promise<string> {
  const [owner, repo] = options.fullName.split("/");
  if (!owner || !repo) {
    throw new Error(`Invalid repository full name: ${options.fullName}`);
  }
  const octokit = createOctokit(options.accessToken);
  try {
    const { data } = await octokit.rest.pulls.create({
      owner,
      repo,
      title: options.title,
      body: options.body,
      head: options.head,
      base: options.base,
    });
    if (!data.html_url) throw new Error("GitHub PR API returned no html_url.");
    return data.html_url;
  } catch (error) {
    throw new Error(octokitErrorMessage(error, "GitHub PR API failed"));
  }
}

/**
 * Applies the finding's fix on a new branch, commits, pushes with the OAuth
 * token when available, and opens a PR via the GitHub REST API.
 */
export async function preparePullRequest(
  project: Project,
  control: Control,
  finding: Finding,
  remediation: Remediation,
): Promise<PullRequestResult> {
  const git = simpleGit({ baseDir: project.rootPath });
  const inside = await git.checkIsRepo();
  if (!inside) {
    throw new Error(
      "Pull request preparation requires a git repository at the project root.",
    );
  }
  if (!finding.fix) {
    throw new Error("This finding has no automatable fix to commit.");
  }

  const handoff = buildDeveloperHandoff(project, control, finding, remediation);
  const shortId = finding.id.slice(0, 8);
  const branch = `complyloop/fix-${finding.checkId}-${shortId}`;

  const currentBranch = (await git.revparse(["--abbrev-ref", "HEAD"])).trim();
  const absolute = path.join(project.rootPath, finding.location.filePath);
  const original = fs.readFileSync(absolute, "utf8");
  const fixed = applyFix(original, finding.fix);

  try {
    const branches = await git.branchLocal();
    if (branches.all.includes(branch)) {
      await git.checkout(branch);
    } else {
      await git.checkoutLocalBranch(branch);
    }
    fs.writeFileSync(absolute, fixed);
    await git.add([finding.location.filePath]);
    try {
      await git.commit([
        handoff.title,
        "Generated by ComplyLoop. Verify with the automated check before merge.",
      ]);
    } catch {
      // Commit may fail if the tree already matches (idempotent retry).
    }
  } catch (error) {
    try {
      await git.checkout(currentBranch);
    } catch {
      /* ignore */
    }
    throw error;
  }

  let prUrl: string | null = null;
  let message = `Branch \`${branch}\` created with the fix committed. Push and open a PR from the developer handoff.`;

  const fullName = project.github?.fullName;
  const token =
    project.ownerUserId != null
      ? getStoredGitHubToken(project.ownerUserId)
      : null;

  if (fullName && token) {
    const remote = githubCloneUrl(fullName, token);
    try {
      await git.push(remote, `HEAD:refs/heads/${branch}`, ["-u"]);
      const base = project.github?.defaultBranch || "main";
      prUrl = await createPullRequestViaApi({
        fullName,
        accessToken: token,
        head: branch,
        base,
        title: handoff.title,
        body: handoff.body,
      });
      message = `Pull request created via GitHub API: ${prUrl}`;
    } catch (error) {
      message =
        error instanceof Error
          ? `Branch \`${branch}\` committed locally; push/PR failed: ${error.message}`
          : `Branch \`${branch}\` committed locally; push/PR failed.`;
    }
  }

  return {
    branch,
    title: handoff.title,
    body: handoff.body,
    committed: true,
    prUrl,
    message,
  };
}
