import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { applyFix } from "@/analysis/fixes";
import type { Control, Finding, Project, Remediation } from "@/core/types";
import { getStoredGitHubToken } from "./github-tokens";
import { githubCloneUrl } from "./connect";
import { buildDeveloperHandoff } from "./handoff";

export interface PullRequestResult {
  branch: string;
  title: string;
  body: string;
  committed: boolean;
  prUrl: string | null;
  message: string;
}

function runGit(rootPath: string, args: string[]): string {
  return execFileSync("git", ["-C", rootPath, ...args], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  }).trim();
}

function isGitRepo(rootPath: string): boolean {
  try {
    runGit(rootPath, ["rev-parse", "--is-inside-work-tree"]);
    return true;
  } catch {
    return false;
  }
}

async function createPullRequestViaApi(options: {
  fullName: string;
  accessToken: string;
  head: string;
  base: string;
  title: string;
  body: string;
}): Promise<string> {
  const response = await fetch(
    `https://api.github.com/repos/${options.fullName}/pulls`,
    {
      method: "POST",
      headers: {
        Accept: "application/vnd.github+json",
        Authorization: `Bearer ${options.accessToken}`,
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "ComplyLoop",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title: options.title,
        body: options.body,
        head: options.head,
        base: options.base,
      }),
    },
  );
  if (!response.ok) {
    const text = await response.text();
    throw new Error(
      `GitHub PR API failed (${response.status}): ${text.slice(0, 300)}`,
    );
  }
  const payload = (await response.json()) as { html_url?: string };
  if (!payload.html_url) throw new Error("GitHub PR API returned no html_url.");
  return payload.html_url;
}

/**
 * Applies the finding's fix on a new branch, commits, pushes with the OAuth
 * token when available, and opens a PR via the GitHub REST API.
 */
export async function preparePullRequest(
  project: Project,
  control: Control,
  finding: Finding,
  remediation: Remediation,
): Promise<PullRequestResult> {
  if (!isGitRepo(project.rootPath)) {
    throw new Error(
      "Pull request preparation requires a git repository at the project root.",
    );
  }
  if (!finding.fix) {
    throw new Error("This finding has no automatable fix to commit.");
  }

  const handoff = buildDeveloperHandoff(project, control, finding, remediation);
  const shortId = finding.id.slice(0, 8);
  const branch = `complyloop/fix-${finding.checkId}-${shortId}`;

  const currentBranch = runGit(project.rootPath, [
    "rev-parse",
    "--abbrev-ref",
    "HEAD",
  ]);
  const absolute = path.join(project.rootPath, finding.location.filePath);
  const original = fs.readFileSync(absolute, "utf8");
  const fixed = applyFix(original, finding.fix);

  try {
    try {
      runGit(project.rootPath, ["checkout", "-b", branch]);
    } catch {
      runGit(project.rootPath, ["checkout", branch]);
    }
    fs.writeFileSync(absolute, fixed);
    runGit(project.rootPath, ["add", "--", finding.location.filePath]);
    try {
      runGit(project.rootPath, [
        "commit",
        "-m",
        handoff.title,
        "-m",
        "Generated by ComplyLoop. Verify with the automated check before merge.",
      ]);
    } catch {
      // Commit may fail if the tree already matches (idempotent retry).
    }
  } catch (error) {
    try {
      runGit(project.rootPath, ["checkout", currentBranch]);
    } catch {
      /* ignore */
    }
    throw error;
  }

  let prUrl: string | null = null;
  let message = `Branch \`${branch}\` created with the fix committed. Push and open a PR from the developer handoff.`;

  const fullName = project.github?.fullName;
  const token =
    project.ownerUserId != null
      ? getStoredGitHubToken(project.ownerUserId)
      : null;

  if (fullName && token) {
    const remote = githubCloneUrl(fullName, token);
    try {
      runGit(project.rootPath, ["push", "-u", remote, `HEAD:refs/heads/${branch}`]);
      const base = project.github?.defaultBranch || "main";
      prUrl = await createPullRequestViaApi({
        fullName,
        accessToken: token,
        head: branch,
        base,
        title: handoff.title,
        body: handoff.body,
      });
      message = `Pull request created via GitHub API: ${prUrl}`;
    } catch (error) {
      message =
        error instanceof Error
          ? `Branch \`${branch}\` committed locally; push/PR failed: ${error.message}`
          : `Branch \`${branch}\` committed locally; push/PR failed.`;
    }
  }

  return {
    branch,
    title: handoff.title,
    body: handoff.body,
    committed: true,
    prUrl,
    message,
  };
}
