import type { RequirementStatus } from "@/core/statuses";
import type { Control, Framework, Project, Requirement } from "@/core/project-types";
import type { EvidenceRecord, Finding, Remediation } from "@/core/finding-types";
import { controlDisplayCodes } from "@/adapters/control-theme";
import { presetById, presetCatalog } from "@/adapters/registry";
import { projectDefaultPresetId } from "@/core/project-preset";
import { formatLocationRef, locationSnippet } from "@/core/location";
import {
  evidenceKindLabel,
  remediationStatusLabel,
  requirementStatusLabel,
} from "@/core/labels";
import { prioritizeClusters } from "@/core/prioritization";
import type { Db } from "./db";
import {
  controlsInScope,
  findingsInScope,
  requirementsInScope,
} from "./assessment-status";
import { evidenceForProject } from "./project-visibility";

export interface ReportInput {
  project: Project;
  framework: Framework;
  controls: Control[];
  requirements: Requirement[];
  findings: Finding[];
  remediations: Remediation[];
  evidence: EvidenceRecord[];
  exportedAt: string;
}

/** Resolves the framework named by the project's assessment preset. */
export function frameworkForProject(
  db: Db,
  project: Project,
): Framework {
  const preset = presetById(projectDefaultPresetId(project, presetCatalog));
  if (preset) {
    const fromPreset = db.frameworks.find(
      (framework) => framework.id === preset.frameworkId,
    );
    if (fromPreset) return fromPreset;
  }
  const fallback = db.frameworks[0];
  if (!fallback) {
    throw new Error("No compliance framework is configured.");
  }
  return fallback;
}

function secondaryReferenceLabel(secondaryCode: string): string {
  if (secondaryCode.startsWith("WCAG")) return "WCAG";
  if (secondaryCode.startsWith("RGAA")) return "RGAA";
  return "Also";
}

/** Builds report input for a project's current store snapshot. */
export function reportInputForProject(db: Db, project: Project): ReportInput {
  const findings = findingsInScope(db.findings, project);
  const framework = frameworkForProject(db, project);
  return {
    project,
    framework,
    controls: controlsInScope(db, project),
    requirements: requirementsInScope(db.requirements, project),
    findings,
    remediations: db.remediations.filter((remediation) =>
      findings.some((finding) => finding.id === remediation.findingId),
    ),
    evidence: evidenceForProject(db.evidence, project.id),
    exportedAt: new Date().toISOString(),
  };
}

export function countRequirementsByStatus(
  requirements: Requirement[],
): Record<RequirementStatus, number> {
  const counts: Record<RequirementStatus, number> = {
    passed: 0,
    failed: 0,
    needs_review: 0,
    not_applicable: 0,
    unable_to_verify: 0,
  };
  for (const requirement of requirements) {
    counts[requirement.status] += 1;
  }
  return counts;
}

function controlById(controls: Control[], id: string): Control | undefined {
  return controls.find((control) => control.id === id);
}

function reportHeaderLines(
  title: string,
  input: ReportInput,
): string[] {
  const { project, framework, exportedAt } = input;
  return [
    `# ${title} — ${project.name}`,
    ``,
    `**Exported:** ${exportedAt}`,
    `**Framework:** ${framework.name} (${framework.version})`,
    `**Project source:** ${project.source}${project.sourceRef ? ` — ${project.sourceRef}` : ""}`,
    project.github?.fullName
      ? `**GitHub repository:** \`${project.github.fullName}\``
      : "",
    ``,
  ].filter((line) => line !== "");
}

function reportFooterLines(): string[] {
  return [
    `---`,
    `_Generated by ComplyLoop. Statuses come from deterministic checks or recorded human decisions; AI content is never the source of truth._`,
    ``,
  ];
}

function projectEvidenceNewestFirst(
  evidence: EvidenceRecord[],
  projectId: string,
): EvidenceRecord[] {
  return evidence
    .filter((record) => record.projectId === projectId || !record.projectId)
    .slice()
    .reverse();
}

/** Engineering-oriented report: open findings, clusters, locations, remediations. */
export function buildEngineeringReportMarkdown(input: ReportInput): string {
  const {
    framework,
    controls,
    requirements,
    findings,
    remediations,
  } = input;
  const openFindings = findings.filter((finding) => finding.status === "open");
  const clusters = prioritizeClusters(openFindings, controls);

  const lines: string[] = [
    ...reportHeaderLines("Engineering report", input),
    `## Summary`,
    ``,
    `| Metric | Count |`,
    `| --- | ---: |`,
    `| Open findings | ${openFindings.length} |`,
    `| Shared root causes | ${clusters.length} |`,
    ``,
  ];

  if (clusters.length > 0) {
    lines.push(`## Shared root causes`);
    lines.push(``);
    for (const cluster of clusters) {
      lines.push(
        `- **${cluster.label}** — ${cluster.findingIds.length} open finding(s)`,
      );
    }
    lines.push(``);
  }

  lines.push(`## Open findings`);
  lines.push(``);

  if (openFindings.length === 0) {
    lines.push(`_No open findings — nothing to fix right now._`);
    lines.push(``);
  } else {
    for (const finding of openFindings) {
      const control = controlById(controls, finding.controlId);
      const requirement = requirements.find(
        (candidate) => candidate.controlId === finding.controlId,
      );
      const remediation = remediations.find(
        (candidate) => candidate.findingId === finding.id,
      );
      const display = control
        ? controlDisplayCodes(control, framework.id)
        : undefined;
      lines.push(
        `### ${display?.code ?? control?.code ?? finding.controlId} @ \`${formatLocationRef(finding.location)}\``,
      );
      lines.push(``);
      if (requirement) {
        lines.push(
          `- **Requirement:** ${requirementStatusLabel(requirement.status)} (${requirement.determination})`,
        );
      }
      lines.push(`- **Severity / confidence:** ${finding.severity} / ${finding.confidence}`);
      lines.push(`- **Check:** \`${finding.checkId}\`${finding.engine ? ` · **Engine:** \`${finding.engine}\`` : ""}`);
      lines.push(`- **Reason:** ${finding.reason}`);
      if (remediation) {
        lines.push(
          `- **Remediation:** ${remediationStatusLabel(remediation.status)}`,
        );
        if (remediation.suggestion) {
          lines.push(
            `- **Suggestion (${remediation.suggestion.provenance}):** ${remediation.suggestion.description}`,
          );
        }
      }
      lines.push(``);
      lines.push("```");
      lines.push(locationSnippet(finding.location));
      lines.push("```");
      lines.push(``);
    }
  }

  lines.push(...reportFooterLines());
  return lines.join("\n");
}

/** Audit-oriented report: requirement status, exceptions, verification evidence. */
export function buildAuditReportMarkdown(input: ReportInput): string {
  const {
    project,
    framework,
    controls,
    requirements,
    findings,
    evidence,
  } = input;
  const counts = countRequirementsByStatus(requirements);
  const openFindings = findings.filter((finding) => finding.status === "open");
  const resolvedFindings = findings.filter((finding) => finding.status === "resolved");
  const dismissedFindings = findings.filter((finding) => finding.status === "dismissed");

  const lines: string[] = [
    ...reportHeaderLines("Audit report", input),
    `## Summary`,
    ``,
    `| Status | Count |`,
    `| --- | ---: |`,
    `| Passed | ${counts.passed} |`,
    `| Failed | ${counts.failed} |`,
    `| Needs review | ${counts.needs_review} |`,
    `| Not applicable | ${counts.not_applicable} |`,
    `| Unable to verify | ${counts.unable_to_verify} |`,
    ``,
    `| Findings | Count |`,
    `| --- | ---: |`,
    `| Open | ${openFindings.length} |`,
    `| Resolved | ${resolvedFindings.length} |`,
    `| Dismissed | ${dismissedFindings.length} |`,
    ``,
    `## Requirements`,
    ``,
  ];

  for (const control of controls) {
    const requirement = requirements.find(
      (candidate) => candidate.controlId === control.id,
    );
    if (!requirement) continue;
    const display = controlDisplayCodes(control, framework.id);
    lines.push(`### ${display.code} — ${control.title}`);
    lines.push(``);
    lines.push(
      `- **${secondaryReferenceLabel(display.secondaryCode)}:** ${display.secondaryCode}`,
    );
    lines.push(
      `- **Status:** ${requirementStatusLabel(requirement.status)} (${requirement.determination})`,
    );
    if (requirement.exception) {
      lines.push(
        `- **Exception:** ${requirement.exception.reason.replace(/_/g, " ")} — ${requirement.exception.note || "(no note)"} (${requirement.exception.at})`,
      );
    }
    lines.push(`- **Updated:** ${requirement.updatedAt}`);
    lines.push(`- ${control.description}`);
    lines.push(``);
  }

  lines.push(`## Evidence trail`);
  lines.push(``);
  const projectEvidence = projectEvidenceNewestFirst(evidence, project.id);

  if (projectEvidence.length === 0) {
    lines.push(`_No evidence recorded._`);
  } else {
    for (const record of projectEvidence) {
      lines.push(
        `- \`${record.at}\` · **${evidenceKindLabel(record.kind)}** — ${record.summary}`,
      );
    }
  }
  lines.push(``);
  lines.push(...reportFooterLines());
  return lines.join("\n");
}