import type { Framework, Project } from "@complyloop/domain/project-types";
import { presetById, presetCatalog } from "@complyloop/adapters/registry";
import { projectDefaultPresetId } from "@/core/project-preset";
import type { Db } from "./db";
import {
  controlsInScope,
  findingsInScope,
  requirementsInScope,
} from "./assessment-status";
import { evidenceForProject } from "./project-visibility";
import {
  composeAuditReport,
  composeEngineeringReport,
  type AuditReportModel,
  type EngineeringReportModel,
  type ReportHeaderModel,
  type ReportInput,
} from "./report-model";
import {
  FINDING_STATUSES,
  REQUIREMENT_STATUSES,
  type FindingStatus,
  type RequirementStatus,
} from "@complyloop/analysis-core/contract/statuses";
import { findingStatusLabel, requirementStatusLabel } from "@/core/labels";

export type { ReportInput };

/** Resolves the framework named by the project's assessment preset. */
export function frameworkForProject(db: Db, project: Project): Framework {
  const preset = presetById(projectDefaultPresetId(project, presetCatalog));
  if (preset) {
    const fromPreset = db.frameworks.find(
      (framework) => framework.id === preset.frameworkId,
    );
    if (fromPreset) return fromPreset;
  }
  const fallback = db.frameworks[0];
  if (!fallback) {
    throw new Error("No compliance framework is configured.");
  }
  return fallback;
}

/** Builds report input for a project's current store snapshot. */
export function reportInputForProject(db: Db, project: Project): ReportInput {
  const findings = findingsInScope(db.findings, project);
  const findingIds = new Set(findings.map((finding) => finding.id));
  const framework = frameworkForProject(db, project);
  return {
    project,
    framework,
    controls: controlsInScope(db, project),
    findings,
    remediations: db.remediations.filter((remediation) =>
      findingIds.has(remediation.findingId),
    ),
    requirements: requirementsInScope(db.requirements, project),
    evidence: evidenceForProject(db.evidence, project.id),
    exportedAt: new Date().toISOString(),
  };
}

function headerMarkdown(header: ReportHeaderModel): string[] {
  return [
    `# ${header.title} — ${header.projectName}`,
    ``,
    `**Exported:** ${header.exportedAt}`,
    `**Framework:** ${header.frameworkName} (${header.frameworkVersion})`,
    `**Project source:** ${header.sourceKind}${header.sourceRef ? ` — ${header.sourceRef}` : ""}`,
    header.githubFullName
      ? `**GitHub repository:** \`${header.githubFullName}\``
      : "",
    ``,
  ].filter((line) => line !== "");
}

function footerMarkdown(): string[] {
  return [
    `---`,
    `_Generated by ComplyLoop. Statuses come from deterministic checks or recorded human decisions; AI content is never the source of truth._`,
    ``,
  ];
}

function renderEngineeringMarkdown(model: EngineeringReportModel): string {
  const lines: string[] = [
    ...headerMarkdown(model.header),
    `## Summary`,
    ``,
    `| Metric | Count |`,
    `| --- | ---: |`,
    `| Open findings | ${model.findings.length} |`,
    `| Shared root causes | ${model.clusters.length} |`,
    ``,
  ];

  if (model.clusters.length > 0) {
    lines.push(`## Shared root causes`);
    lines.push(``);
    for (const cluster of model.clusters) {
      lines.push(
        `- **${cluster.label}** — ${cluster.findingCount} open finding(s)`,
      );
    }
    lines.push(``);
  }

  lines.push(`## Open findings`);
  lines.push(``);

  if (model.findings.length === 0) {
    lines.push(`_No open findings — nothing to fix right now._`);
    lines.push(``);
  } else {
    for (const finding of model.findings) {
      lines.push(`### ${finding.code} @ \`${finding.locationRef}\``);
      lines.push(``);
      if (finding.requirementLine) {
        lines.push(`- **Requirement:** ${finding.requirementLine}`);
      }
      lines.push(
        `- **Severity / confidence:** ${finding.severityClass} / ${finding.confidence}`,
      );
      lines.push(
        `- **Check:** \`${finding.checkId}\`${finding.engine ? ` · **Engine:** \`${finding.engine}\`` : ""}`,
      );
      lines.push(`- **Reason:** ${finding.reason}`);
      if (finding.remediationStatus) {
        lines.push(`- **Remediation:** ${finding.remediationStatus}`);
      }
      if (finding.suggestion) {
        lines.push(
          `- **Suggestion (${finding.suggestion.provenance}):** ${finding.suggestion.description}`,
        );
      }
      lines.push(``);
      lines.push("```");
      lines.push(finding.snippet);
      lines.push("```");
      lines.push(``);
    }
  }

  lines.push(...footerMarkdown());
  return lines.join("\n");
}

function statusCountRows(
  counts: Record<RequirementStatus, number>,
): string[] {
  return REQUIREMENT_STATUSES.map(
    (status) => `| ${requirementStatusLabel(status)} | ${counts[status]} |`,
  );
}

function findingCountRows(counts: Record<FindingStatus, number>): string[] {
  return FINDING_STATUSES.map(
    (status) => `| ${findingStatusLabel(status)} | ${counts[status]} |`,
  );
}

function renderAuditMarkdown(model: AuditReportModel): string {
  const { statusCounts, findingCounts } = model;
  const lines: string[] = [
    ...headerMarkdown(model.header),
    `## Summary`,
    ``,
    `| Status | Count |`,
    `| --- | ---: |`,
    ...statusCountRows(statusCounts),
    ``,
    `| Findings | Count |`,
    `| --- | ---: |`,
    ...findingCountRows(findingCounts),
    ``,
    `## Requirements`,
    ``,
  ];

  for (const requirement of model.requirements) {
    lines.push(`### ${requirement.code} — ${requirement.title}`);
    lines.push(``);
    lines.push(
      `- **${requirement.secondaryLabel}:** ${requirement.secondaryCode}`,
    );
    lines.push(
      `- **Status:** ${requirement.statusLabel} (${requirement.determinationLabel})`,
    );
    if (requirement.exception) {
      lines.push(
        `- **Exception:** ${requirement.exception.reason} — ${requirement.exception.note} (${requirement.exception.at})`,
      );
    }
    lines.push(`- **Updated:** ${requirement.updatedAt}`);
    lines.push(`- ${requirement.description}`);
    lines.push(``);
  }

  lines.push(`## Evidence trail`);
  lines.push(``);
  if (model.evidence.length === 0) {
    lines.push(`_No evidence recorded._`);
  } else {
    for (const record of model.evidence) {
      lines.push(
        `- \`${record.at}\` · **${record.kindLabel}** — ${record.summary}`,
      );
    }
  }
  lines.push(``);
  lines.push(...footerMarkdown());
  return lines.join("\n");
}

/** Engineering-oriented report: open findings, clusters, locations, remediations. */
export function buildEngineeringReportMarkdown(input: ReportInput): string {
  return renderEngineeringMarkdown(composeEngineeringReport(input));
}

/** Audit-oriented report: requirement status, exceptions, verification evidence. */
export function buildAuditReportMarkdown(input: ReportInput): string {
  return renderAuditMarkdown(composeAuditReport(input));
}
