import "server-only";

import {
  FINDING_STATUSES,
  type FindingStatus,
  REQUIREMENT_STATUSES,
  type RequirementStatus,
} from "@complyloop/analysis-core/contract/statuses";

import { formatDateTimeWithZone } from "@/core/datetime";
import {
  findingStatusDisplay,
  requirementStatusDisplay,
  severityDisplay,
} from "@/core/display";

import {
  type AuditReportModel,
  composeAuditReport,
  composeEngineeringReport,
  type EngineeringFindingCard,
  type EngineeringReportModel,
  projectSourceLabel,
  type ReportHeaderModel,
  type ReportInput,
} from "./report-model";

/** Collapses hard newlines so analyzer/user text cannot break markdown structure. */
function inline(text: string): string {
  return text.replace(/\s*\n\s*/g, " ").trim();
}

/**
 * Escapes untrusted text for prose contexts (headings, list items, table
 * cells). `inline()` already removes newlines, so values can never start a
 * line — only mid-line structural characters need escaping: backticks (inline
 * code spans), `[` (links/images — escaping it alone prevents any link from
 * forming), `|` (table cells), and the escape character itself. Everything
 * else (`*`, `_`, `()`, `#`, …) is cosmetic mid-line and left alone so
 * controlled vocabulary like "WCAG 2.2 (accessibility standard)" stays clean.
 */
function mdProse(text: string): string {
  return inline(text).replace(/[\\`\[|]/g, (char) => `\\${char}`);
}

/**
 * Sanitizes untrusted text for inline-code contexts (already wrapped in
 * backticks by the caller). Backslash escapes render literally inside code
 * spans, so instead neutralize the only structural character — the backtick.
 */
function mdCode(text: string): string {
  return inline(text).replace(/`/g, "'");
}

function headerMarkdown(header: ReportHeaderModel): string[] {
  const lines = [
    `# ${mdProse(header.title)} — ${mdProse(header.projectName)}`,
    ``,
    `- **Exported:** ${formatDateTimeWithZone(header.exportedAt)}`,
    `- **Framework:** ${mdProse(header.frameworkName)} (${mdProse(header.frameworkVersion)})`,
    `- **Project source:** ${mdProse(projectSourceLabel(header))}`,
  ];
  if (header.githubFullName) {
    lines.push(`- **GitHub repository:** \`${mdCode(header.githubFullName)}\``);
  }
  lines.push(``);
  return lines;
}

function footerMarkdown(): string[] {
  return [
    `---`,
    `_Generated by ComplyLoop. Statuses come from deterministic checks or recorded human decisions; AI content is never the source of truth._`,
    ``,
  ];
}

function statusCountRows(counts: Record<RequirementStatus, number>): string[] {
  return REQUIREMENT_STATUSES.map(
    (status) =>
      `| ${mdProse(requirementStatusDisplay(status).label)} | ${counts[status]} |`,
  );
}

function findingCountRows(counts: Record<FindingStatus, number>): string[] {
  return FINDING_STATUSES.map(
    (status) =>
      `| ${mdProse(findingStatusDisplay(status).label)} | ${counts[status]} |`,
  );
}

/** Fenced block whose fence outlengths any backtick run, so a snippet cannot break out. */
function fencedBlock(text: string, language: string): string[] {
  const longestRun = Math.max(
    0,
    ...[...text.matchAll(/`+/g)].map((match) => match[0].length),
  );
  const fence = "`".repeat(Math.max(3, longestRun + 1));
  return [`${fence}${language}`, text, fence];
}

function engineeringSeverityRows(findings: EngineeringFindingCard[]): string[] {
  return (["critical", "serious", "moderate", "minor"] as const)
    .filter((severity) =>
      findings.some((finding) => finding.severityClass === severity),
    )
    .map((severity) => {
      const count = findings.filter(
        (finding) => finding.severityClass === severity,
      ).length;
      return `| ${mdProse(severityDisplay(severity).label)} | ${count} |`;
    });
}

function renderEngineeringMarkdown(model: EngineeringReportModel): string {
  const lines: string[] = [
    ...headerMarkdown(model.header),
    `## Summary`,
    ``,
    `| Metric | Count |`,
    `| --- | ---: |`,
    `| Open findings | ${model.findings.length} |`,
    `| Shared root causes | ${model.clusters.length} |`,
    ``,
  ];

  const severityRows = engineeringSeverityRows(model.findings);
  if (severityRows.length > 0) {
    lines.push(`### Findings by severity`);
    lines.push(``);
    lines.push(`| Severity | Count |`);
    lines.push(`| --- | ---: |`);
    lines.push(...severityRows);
    lines.push(``);
  }

  lines.push(`## Shared root causes`);
  lines.push(``);
  if (model.clusters.length === 0) {
    lines.push(`_No shared root causes detected._`);
  } else {
    for (const cluster of model.clusters) {
      lines.push(
        `- **${mdProse(cluster.checkId)}** — ${cluster.findingCount} finding(s) at \`${mdCode(cluster.sharedLocation)}\``,
      );
    }
  }
  lines.push(``);

  lines.push(`## Open findings`);
  lines.push(``);

  if (model.findings.length === 0) {
    lines.push(`_No open findings — nothing to fix right now._`);
    lines.push(``);
  } else {
    model.findings.forEach((finding, index) => {
      lines.push(
        `### ${index + 1}. ${mdProse(finding.code)} — \`${mdCode(finding.locationRef)}\``,
      );
      lines.push(``);
      lines.push(`- **Severity:** ${mdProse(finding.severity)}`);
      lines.push(`- **Confidence:** ${mdProse(finding.confidence)}`);
      lines.push(
        `- **Check:** \`${mdCode(finding.checkId)}\`${finding.engine ? ` · **Engine:** \`${mdCode(finding.engine)}\`` : ""}`,
      );
      if (finding.requirementLine) {
        lines.push(`- **Requirement:** ${mdProse(finding.requirementLine)}`);
      }
      if (finding.remediationStatus) {
        lines.push(`- **Remediation:** ${mdProse(finding.remediationStatus)}`);
      }
      lines.push(``);
      lines.push(`**Reason:** ${mdProse(finding.reason)}`);
      lines.push(``);
      lines.push(...fencedBlock(finding.snippet, finding.language));
      lines.push(``);
      if (finding.suggestion) {
        lines.push(
          `**Suggested change (${mdProse(finding.suggestion.provenance)}):** ${mdProse(finding.suggestion.description)}`,
        );
        lines.push(``);
        lines.push(
          ...fencedBlock(finding.suggestion.proposedSnippet, finding.language),
        );
        lines.push(``);
      }
      if (index < model.findings.length - 1) {
        lines.push(`---`);
        lines.push(``);
      }
    });
  }

  lines.push(...footerMarkdown());
  return lines.join("\n");
}

function renderAuditMarkdown(model: AuditReportModel): string {
  const { statusCounts, findingCounts } = model;
  const lines: string[] = [
    ...headerMarkdown(model.header),
    `## Summary`,
    ``,
    `| Status | Count |`,
    `| --- | ---: |`,
    ...statusCountRows(statusCounts),
    ``,
    `| Findings | Count |`,
    `| --- | ---: |`,
    ...findingCountRows(findingCounts),
    ``,
    `## Requirements`,
    ``,
  ];

  for (const requirement of model.requirements) {
    lines.push(
      `### ${mdProse(requirement.code)} — ${mdProse(requirement.title)}`,
    );
    lines.push(``);
    lines.push(
      `- **${mdProse(requirement.secondaryLabel)}:** ${mdProse(requirement.secondaryCode)}`,
    );
    lines.push(
      `- **Status:** ${mdProse(requirement.statusLabel)} (${mdProse(requirement.determinationLabel)})`,
    );
    if (requirement.exception) {
      lines.push(
        `- **Exception:** ${mdProse(requirement.exception.reason)} — ${mdProse(requirement.exception.note)} (${formatDateTimeWithZone(requirement.exception.at)})`,
      );
    }
    lines.push(
      `- **Updated:** ${formatDateTimeWithZone(requirement.updatedAt)}`,
    );
    lines.push(`- ${mdProse(requirement.description)}`);
    lines.push(``);
  }

  lines.push(`## Evidence trail`);
  lines.push(``);
  if (model.evidenceTruncated) {
    lines.push(
      `_Showing the latest ${model.evidence.length} of ${model.evidenceTotal} evidence records — download raw JSON for the full trail._`,
    );
    lines.push(``);
  }
  if (model.evidence.length === 0) {
    lines.push(`_No evidence recorded._`);
  } else {
    for (const record of model.evidence) {
      lines.push(
        `- ${formatDateTimeWithZone(record.at)} · **${mdProse(record.kindLabel)}** — ${mdProse(record.summary)}`,
      );
    }
  }
  lines.push(``);
  lines.push(...footerMarkdown());
  return lines.join("\n");
}

/** Engineering-oriented report: open findings, clusters, locations, remediations. */
export function buildEngineeringReportMarkdown(input: ReportInput): string {
  return renderEngineeringMarkdown(composeEngineeringReport(input));
}

/** Audit-oriented report: requirement status, exceptions, verification evidence. */
export function buildAuditReportMarkdown(input: ReportInput): string {
  return renderAuditMarkdown(composeAuditReport(input));
}
