import type { Control, Framework } from "@/core/project-types";

export const rgaaFramework: Framework = {
  id: "fw-rgaa-4",
  name: "RGAA 4 (French accessibility standard)",
  version: "2026.3",
};

export const rgaaControls: Control[] = [
  {
    id: "ctl-img-alt",
    frameworkId: rgaaFramework.id,
    code: "RGAA 1.1",
    secondaryCode: "WCAG 1.1.1",
    title: "Images have a text alternative",
    description:
      "Every informative image exposes a text alternative; decorative images are explicitly marked as such.",
    checkId: "img-alt",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-button-name",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.9",
    secondaryCode: "WCAG 4.1.2",
    title: "Buttons have an accessible name",
    description:
      "Every button exposes a name describing its action, via text content or an ARIA label.",
    checkId: "button-name",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-link-name",
    frameworkId: rgaaFramework.id,
    code: "RGAA 6.2",
    secondaryCode: "WCAG 2.4.4",
    title: "Links have an accessible name",
    description:
      "Every link exposes a name describing its destination, via text content, image alternatives, or an ARIA label.",
    checkId: "anchor-name",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-html-lang",
    frameworkId: rgaaFramework.id,
    code: "RGAA 8.3",
    secondaryCode: "WCAG 3.1.1",
    title: "The page declares its language",
    description:
      "The document's default human language is programmatically determinable via the lang attribute.",
    checkId: "html-lang",
    complianceWeight: 1.5,
  },
  {
    id: "ctl-html-lang-valid",
    frameworkId: rgaaFramework.id,
    code: "RGAA 8.4",
    secondaryCode: "WCAG 3.1.1",
    title: "The page language code is valid",
    description:
      "The lang attribute on <html> uses a valid BCP 47 language tag.",
    checkId: "html-lang-valid",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-focus-order",
    frameworkId: rgaaFramework.id,
    code: "RGAA 12.8",
    secondaryCode: "WCAG 2.4.3",
    title: "Focus order is logical",
    description:
      "Keyboard focus follows the natural document order; no element forces a custom order with a positive tabindex.",
    checkId: "positive-tabindex",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-input-label",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.1",
    secondaryCode: "WCAG 3.3.2",
    title: "Form fields have labels",
    description:
      "Every form field exposes a label telling users what to enter, via <label> association or ARIA attributes.",
    checkId: "input-label",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-heading-order",
    frameworkId: rgaaFramework.id,
    code: "RGAA 9.1",
    secondaryCode: "WCAG 1.3.1",
    title: "Heading levels follow a logical order",
    description:
      "Headings do not skip levels in the document outline (e.g. h2 must not jump to h4).",
    checkId: "heading-order",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-empty-heading",
    frameworkId: rgaaFramework.id,
    code: "RGAA 9.1",
    secondaryCode: "WCAG 1.3.1",
    title: "Headings have accessible names",
    description:
      "Every heading exposes text or an ARIA name so the outline is usable.",
    checkId: "empty-heading",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-iframe-title",
    frameworkId: rgaaFramework.id,
    code: "RGAA 2.1",
    secondaryCode: "WCAG 4.1.2",
    title: "Frames have a title",
    description:
      "Every iframe exposes a title describing its purpose to assistive technologies.",
    checkId: "iframe-title",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-autoplay-media",
    frameworkId: rgaaFramework.id,
    code: "RGAA 4.10",
    secondaryCode: "WCAG 1.4.2",
    title: "Media does not autoplay",
    description:
      "Audio and video do not start automatically; users control playback.",
    checkId: "autoplay-media",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-duplicate-id",
    frameworkId: rgaaFramework.id,
    code: "RGAA 8.2",
    secondaryCode: "WCAG 4.1.2",
    title: "IDs are unique",
    description:
      "id attributes are unique within the generated tree so labels and ARIA references resolve correctly.",
    checkId: "duplicate-id",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-form-error-association",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.10",
    secondaryCode: "WCAG 3.3.1",
    title: "Form errors are associated with fields",
    description:
      "When a field is invalid, its error message is programmatically associated (e.g. aria-describedby).",
    checkId: "form-error-association",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-aria-hidden-focusable",
    frameworkId: rgaaFramework.id,
    code: "RGAA 8.9",
    secondaryCode: "WCAG 4.1.2",
    title: "Hidden elements are not focusable",
    description:
      "Elements with aria-hidden must not be reachable by keyboard focus.",
    checkId: "aria-hidden-focusable",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-aria-role",
    frameworkId: rgaaFramework.id,
    code: "RGAA 7.1",
    secondaryCode: "WCAG 4.1.2",
    title: "ARIA roles are valid",
    description:
      "role values are concrete ARIA roles, not abstract or invented names.",
    checkId: "aria-role",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-aria-props",
    frameworkId: rgaaFramework.id,
    code: "RGAA 7.1",
    secondaryCode: "WCAG 4.1.2",
    title: "ARIA attributes are valid",
    description:
      "aria-* attributes exist in the ARIA specification (no typos or unknown properties).",
    checkId: "aria-props",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-aria-required-attr",
    frameworkId: rgaaFramework.id,
    code: "RGAA 7.1",
    secondaryCode: "WCAG 4.1.2",
    title: "Roles include required ARIA properties",
    description:
      "An explicit ARIA role exposes every property that role requires (e.g. checkbox needs aria-checked).",
    checkId: "aria-required-attr",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-no-autofocus",
    frameworkId: rgaaFramework.id,
    code: "RGAA 13.2",
    secondaryCode: "WCAG 3.2.1",
    title: "Pages do not steal focus on load",
    description:
      "autoFocus is not used; keyboard and screen reader users keep control of where focus starts.",
    checkId: "no-autofocus",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-keyboard-interaction",
    frameworkId: rgaaFramework.id,
    code: "RGAA 7.3",
    secondaryCode: "WCAG 2.1.1",
    title: "Scripts are operable from the keyboard",
    description:
      "Scripts and custom widgets are focusable, have an interactive role when needed, and expose equivalent keyboard events.",
    checkId: "keyboard-interaction",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-color-contrast",
    frameworkId: rgaaFramework.id,
    code: "RGAA 3.2",
    secondaryCode: "WCAG 1.4.3",
    title: "Text contrast meets 4.5:1",
    description:
      "Foreground and background color of text meets WCAG AA contrast (measured on the rendered page).",
    checkId: "color-contrast",
    complianceWeight: 1.5,
  },
  {
    id: "ctl-document-title",
    frameworkId: rgaaFramework.id,
    code: "RGAA 8.5",
    secondaryCode: "WCAG 2.4.2",
    title: "The page has a title",
    description:
      "The rendered document exposes a non-empty <title> describing the page.",
    checkId: "document-title",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-bypass",
    frameworkId: rgaaFramework.id,
    code: "RGAA 12.7",
    secondaryCode: "WCAG 2.4.1",
    title: "A mechanism skips repeated blocks",
    description:
      "The page provides a skip link, landmark, or heading structure so keyboard users can bypass repeated chrome.",
    checkId: "bypass",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-landmark-one-main",
    frameworkId: rgaaFramework.id,
    code: "RGAA 12.6",
    secondaryCode: "WCAG 1.3.1",
    title: "The page has one main landmark",
    description:
      "The rendered page exposes exactly one main landmark for the primary content.",
    checkId: "landmark-one-main",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-nested-interactive",
    frameworkId: rgaaFramework.id,
    code: "RGAA 8.9",
    secondaryCode: "WCAG 4.1.2",
    title: "Interactive controls are not nested",
    description:
      "Buttons, links, and other widgets are not placed inside other widgets (measured on the rendered tree).",
    checkId: "nested-interactive",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-target-size",
    frameworkId: rgaaFramework.id,
    code: "WCAG 2.5.8",
    secondaryCode: "WCAG 2.5.8",
    title: "Pointer targets are large enough",
    description:
      "Interactive targets meet the WCAG 2.2 minimum size (24×24 CSS pixels) on the rendered page.",
    checkId: "target-size",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-meta-viewport",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.4",
    secondaryCode: "WCAG 1.4.4",
    title: "Viewport allows zoom",
    description:
      "The viewport meta tag must not disable zooming (no user-scalable=no or maximum-scale below 2).",
    checkId: "meta-viewport",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-resize-text",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.4",
    secondaryCode: "WCAG 1.4.4",
    title: "Text remains readable at 200% resize",
    description:
      "Content stays readable when text is enlarged to 200% without clipping or horizontal scrolling.",
    checkId: "resize-text",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-list-structure",
    frameworkId: rgaaFramework.id,
    code: "RGAA 9.3",
    secondaryCode: "WCAG 1.3.1",
    title: "Lists use correct structure",
    description:
      "List items are children of ul/ol/menu, and list containers only contain li children.",
    checkId: "list-structure",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-autocomplete-valid",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.13",
    secondaryCode: "WCAG 1.3.5",
    title: "Autocomplete tokens are valid",
    description:
      "Form controls that declare autocomplete use valid HTML autofill tokens so browsers and ATs can identify the expected input purpose.",
    checkId: "autocomplete-valid",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-table-headers",
    frameworkId: rgaaFramework.id,
    code: "RGAA 5.7",
    secondaryCode: "WCAG 1.3.1",
    title: "Table data cells have headers",
    description:
      "Every data cell in a data table is associated with one or more header cells (th/id or scope) so the relationship is programmatically determinable.",
    checkId: "table-headers",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-page-heading",
    frameworkId: rgaaFramework.id,
    code: "RGAA 9.2",
    secondaryCode: "WCAG 2.4.6",
    title: "The page has a top-level heading",
    description:
      "Each page exposes at least one heading (h1) so its structure is perceivable to assistive technology.",
    checkId: "page-heading",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-content-region",
    frameworkId: rgaaFramework.id,
    code: "RGAA 9.2",
    secondaryCode: "WCAG 1.3.1",
    title: "Page content sits inside landmarks",
    description:
      "All page content is contained within landmark regions (header, nav, main, aside, footer) so its structure is conveyed to assistive technology.",
    checkId: "content-region",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-label-in-name",
    frameworkId: rgaaFramework.id,
    code: "WCAG 2.5.3",
    secondaryCode: "WCAG 2.5.3",
    title: "Visible label is contained in the accessible name",
    description:
      "For components with a visible text label, the accessible name includes that visible label (punctuation and letter-case ignored).",
    checkId: "label-in-name",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-lang-parts",
    frameworkId: rgaaFramework.id,
    code: "RGAA 8.8",
    secondaryCode: "WCAG 3.1.2",
    title: "Language-change codes are valid",
    description:
      "Each lang attribute on a passage in another language uses a valid BCP 47 language tag.",
    checkId: "lang-parts",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-aria-roledescription",
    frameworkId: rgaaFramework.id,
    code: "RGAA 7.1",
    secondaryCode: "WCAG 4.1.2",
    title: "aria-roledescription values are valid",
    description:
      "Elements that use aria-roledescription provide a non-empty, meaningful value that does not duplicate the implicit role name.",
    checkId: "aria-roledescription",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-presentation-role",
    frameworkId: rgaaFramework.id,
    code: "RGAA 8.9",
    secondaryCode: "WCAG 4.1.2",
    title: "Presentation role does not hide focusable content",
    description:
      "Elements with role='presentation' or role='none' do not contain focusable descendants that would become inaccessible.",
    checkId: "presentation-role",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-no-auto-refresh",
    frameworkId: rgaaFramework.id,
    code: "RGAA 13.1",
    secondaryCode: "WCAG 2.2.1",
    title: "No unexpected time limits or redirects",
    description:
      "The page does not auto-refresh or redirect after a time limit without user control (meta refresh is removed).",
    checkId: "no-auto-refresh",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-no-orientation-lock",
    frameworkId: rgaaFramework.id,
    code: "RGAA 13.9",
    secondaryCode: "WCAG 1.3.4",
    title: "Content is not restricted to one display orientation",
    description:
      "Content does not lock to portrait or landscape; it adapts to the orientation the user prefers (unless an orientation is essential).",
    checkId: "no-orientation-lock",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-landmark-unique",
    frameworkId: rgaaFramework.id,
    code: "RGAA 12.6",
    secondaryCode: "WCAG 1.3.1",
    title: "Landmarks have unique, descriptive names",
    description:
      "When more than one landmark of the same type is used (e.g. multiple nav), each has a distinct accessible name so users can tell them apart.",
    checkId: "landmark-unique",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-pointer-gesture",
    frameworkId: rgaaFramework.id,
    code: "RGAA 13.10",
    secondaryCode: "WCAG 2.5.1",
    title: "Pointer gestures have a keyboard alternative",
    description:
      "Functionality operated through a path-based pointer gesture (drag, swipe) also works with a single-pointer or keyboard action.",
    checkId: "pointer-gesture",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-pointer-cancellation",
    frameworkId: rgaaFramework.id,
    code: "RGAA 13.11",
    secondaryCode: "WCAG 2.5.2",
    title: "Pointer actions are abortable",
    description:
      "A pointerdown that starts an action provides a pointercancel/up path so the action can be aborted before completion.",
    checkId: "pointer-cancellation",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-motion-actuation",
    frameworkId: rgaaFramework.id,
    code: "RGAA 13.12",
    secondaryCode: "WCAG 2.5.4",
    title: "Motion actuation has a non-motion alternative",
    description:
      "Functions triggered by device motion or orientation (shake, tilt) can also be operated without the motion (button/keyboard).",
    checkId: "motion-actuation",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-focus-context-change",
    frameworkId: rgaaFramework.id,
    code: "RGAA 7.4",
    secondaryCode: "WCAG 3.2.1",
    title: "Focus does not change context",
    description:
      "Receiving focus does not unexpectedly change context (navigate, submit, open a dialog) without warning.",
    checkId: "focus-context-change",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-input-context-change",
    frameworkId: rgaaFramework.id,
    code: "RGAA 7.4",
    secondaryCode: "WCAG 3.2.2",
    title: "Input does not change context",
    description:
      "Changing or entering input does not unexpectedly change context (navigate, submit) without warning or a confirmation step.",
    checkId: "input-context-change",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-sensory-characteristics",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.9",
    secondaryCode: "WCAG 1.3.3",
    title: "Instructions do not rely on sensory characteristics",
    description:
      "Instructions are not conveyed by color, shape, size, sound, or position alone; they are also available as text.",
    checkId: "sensory-characteristics",
    complianceWeight: 1.0,
  },
  {
    id: "ctl-image-of-text",
    frameworkId: rgaaFramework.id,
    code: "RGAA 1.8",
    secondaryCode: "WCAG 1.4.5",
    title: "Text is not presented as an image",
    description:
      "Information conveyed as an image of text (CSS background text, role='img' with text) is also available as real text.",
    checkId: "image-of-text",
    complianceWeight: 1.0,
  },
  {
    id: "ctl-error-suggestion",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.11",
    secondaryCode: "WCAG 3.3.3",
    title: "Errors suggest a correction",
    description:
      "When input is invalid, the error identifies the problem and suggests how to fix it (not just that it is wrong).",
    checkId: "error-suggestion",
    complianceWeight: 1.0,
  },
  {
    id: "ctl-video-caption",
    frameworkId: rgaaFramework.id,
    code: "RGAA 4.3",
    secondaryCode: "WCAG 1.2.2",
    title: "Pre-recorded video has captions",
    description:
      "Synchronized captions are provided for pre-recorded video with audio, so users who cannot hear the soundtrack can follow it.",
    checkId: "video-caption",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-audio-caption",
    frameworkId: rgaaFramework.id,
    code: "RGAA 4.1",
    secondaryCode: "WCAG 1.2.1",
    title: "Pre-recorded audio has a text alternative",
    description:
      "Audio-only media exposes a transcript, captions, or descriptions track equivalent to the spoken content.",
    checkId: "audio-caption",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-media-controls-present",
    frameworkId: rgaaFramework.id,
    code: "RGAA 4.11",
    secondaryCode: "WCAG 2.1.1",
    title: "Temporal media is operable from the keyboard",
    description:
      "Video and audio expose native controls or a custom player with keyboard support.",
    checkId: "media-controls-present",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-no-blink-marquee",
    frameworkId: rgaaFramework.id,
    code: "RGAA 13.8",
    secondaryCode: "WCAG 2.2.2",
    title: "Moving or blinking content can be paused",
    description:
      "Marquee, blink, and other moving content is not used without a way for the user to pause, stop, or hide it.",
    checkId: "no-blink-marquee",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-text-spacing",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.12",
    secondaryCode: "WCAG 1.4.12",
    title: "Text spacing can be overridden",
    description:
      "Line height, letter spacing, word spacing, and paragraph spacing must not be locked with !important so users can adapt them.",
    checkId: "text-spacing",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-use-of-color",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.6",
    secondaryCode: "WCAG 1.4.1",
    title: "Links are distinguishable from surrounding text",
    description:
      "Links in text blocks are distinguishable without relying only on color (underline, icon, or text).",
    checkId: "use-of-color",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-empty-th",
    frameworkId: rgaaFramework.id,
    code: "RGAA 5.6",
    secondaryCode: "WCAG 1.3.1",
    title: "Table headers have accessible names",
    description:
      "Every column or row header cell exposes a name so the relationship to data cells is programmatically determinable.",
    checkId: "empty-th",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-dialog-name",
    frameworkId: rgaaFramework.id,
    code: "RGAA 7.1",
    secondaryCode: "WCAG 4.1.2",
    title: "Dialogs have an accessible name",
    description:
      "Every dialog and alertdialog exposes a name describing its purpose.",
    checkId: "dialog-name",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-tab-name",
    frameworkId: rgaaFramework.id,
    code: "RGAA 7.1",
    secondaryCode: "WCAG 4.1.2",
    title: "Tabs have an accessible name",
    description:
      "Every tab in a tablist exposes a name so users can tell the panels apart.",
    checkId: "tab-name",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-summary-name",
    frameworkId: rgaaFramework.id,
    code: "RGAA 7.1",
    secondaryCode: "WCAG 4.1.2",
    title: "Disclosure summaries have an accessible name",
    description:
      "Every summary / disclosure control exposes a name describing what it expands.",
    checkId: "summary-name",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-frame-keyboard",
    frameworkId: rgaaFramework.id,
    code: "RGAA 7.3",
    secondaryCode: "WCAG 2.1.1",
    title: "Frames with interactive content are keyboard accessible",
    description:
      "Iframes that contain focusable content must themselves be reachable or must not trap keyboard users.",
    checkId: "frame-keyboard",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-p-as-heading",
    frameworkId: rgaaFramework.id,
    code: "RGAA 9.1",
    secondaryCode: "WCAG 1.3.1",
    title: "Visual headings use heading markup",
    description:
      "Text styled as a heading is marked up as a heading so the outline matches the visual hierarchy.",
    checkId: "p-as-heading",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-doctype",
    frameworkId: rgaaFramework.id,
    code: "RGAA 8.1",
    secondaryCode: "WCAG 4.1.1",
    title: "The page declares a document type",
    description:
      "Each page has a doctype so browsers parse it in standards mode.",
    checkId: "doctype",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-fieldset-legend",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.6",
    secondaryCode: "WCAG 1.3.1",
    title: "Related form fields are grouped with a legend",
    description:
      "Radio groups and other related fields are wrapped in a fieldset (or labelled group) with a legend.",
    checkId: "fieldset-legend",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-autocomplete-purpose",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.13",
    secondaryCode: "WCAG 1.3.5",
    title: "Identity fields declare their input purpose",
    description:
      "Email, password, name, telephone, and address fields include an autocomplete token so browsers can fill them.",
    checkId: "autocomplete-purpose",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-no-accesskey",
    frameworkId: rgaaFramework.id,
    code: "RGAA 12.10",
    secondaryCode: "WCAG 2.1.4",
    title: "Single-key shortcuts are not hard-coded",
    description:
      "accessKey / single-character shortcuts are not used; they conflict with assistive technology and cannot be remapped.",
    checkId: "no-accesskey",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-optgroup",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.8",
    secondaryCode: "WCAG 1.3.1",
    title: "Option groups have a label",
    description:
      "Each optgroup exposes a label naming the category; grouping presence is not inferred from a long ungrouped select.",
    checkId: "optgroup",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-table-caption",
    frameworkId: rgaaFramework.id,
    code: "RGAA 5.4",
    secondaryCode: "WCAG 1.3.1",
    title: "Data tables have a caption",
    description:
      "Every data table (a table that has header cells) exposes a caption or accessible name. Layout tables are not applicable.",
    checkId: "table-caption",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-table-summary",
    frameworkId: rgaaFramework.id,
    code: "RGAA 5.1",
    secondaryCode: "WCAG 1.3.1",
    title: "Complex data tables have a summary",
    description:
      "Complex tables expose a summary or aria-describedby so users understand structure before reading cells.",
    checkId: "table-summary",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-th-scope",
    frameworkId: rgaaFramework.id,
    code: "RGAA 5.7",
    secondaryCode: "WCAG 1.3.1",
    title: "Table headers declare row or column scope",
    description:
      "Each header cell uses scope or is referenced through headers/id so its relationship to data cells is determinable.",
    checkId: "th-scope",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-layout-table-markup",
    frameworkId: rgaaFramework.id,
    code: "RGAA 5.8",
    secondaryCode: "WCAG 1.3.1",
    title: "Layout tables do not use data-table markup",
    description:
      "Tables used for layout (role presentation/none) must not contain th, caption, headers, or scope.",
    checkId: "layout-table-markup",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-svg-name",
    frameworkId: rgaaFramework.id,
    code: "RGAA 1.1",
    secondaryCode: "WCAG 1.1.1",
    title: "Standalone SVGs have a text alternative",
    description:
      "Informative SVG graphics expose a name via title or ARIA; decorative SVGs are marked presentation or hidden.",
    checkId: "svg-name",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-figure-caption",
    frameworkId: rgaaFramework.id,
    code: "RGAA 1.9",
    secondaryCode: "WCAG 1.1.1",
    title: "Figure captions are programmatically associated",
    description:
      "When a figure has caption text, it lives in figcaption so the association is determinable. Caption quality is a separate human control.",
    checkId: "figure-caption",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-image-detailed-description",
    frameworkId: rgaaFramework.id,
    code: "RGAA 1.6",
    secondaryCode: "WCAG 1.1.1",
    title: "Complex images expose a detailed description",
    description:
      "Likely complex images link to a long description via aria-describedby or aria-details. Pertinence is human-reviewed.",
    checkId: "image-detailed-description",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-redundant-role",
    frameworkId: rgaaFramework.id,
    code: "RGAA 8.9",
    secondaryCode: "WCAG 1.3.1",
    title: "Native elements do not repeat their implicit role",
    description:
      "role on a host must not duplicate the implicit ARIA role (for example role=button on button).",
    checkId: "redundant-role",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-noninteractive-tabindex",
    frameworkId: rgaaFramework.id,
    code: "RGAA 12.8",
    secondaryCode: "WCAG 2.1.1",
    title: "Non-interactive elements are not in the tab order",
    description:
      "tabIndex 0 is reserved for native controls and custom widgets that also have a role and keyboard handling.",
    checkId: "noninteractive-tabindex",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-aria-activedescendant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 7.1",
    secondaryCode: "WCAG 4.1.2",
    title: "aria-activedescendant hosts are focusable",
    description:
      "An element that manages aria-activedescendant is itself keyboard-focusable so the active descendant can be announced.",
    checkId: "aria-activedescendant",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-focus-visible",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.7",
    secondaryCode: "WCAG 2.4.7",
    title: "Focused controls have a visible focus indicator",
    description:
      "Keyboard focus is visually distinguishable via outline, ring, or an equivalent style.",
    checkId: "focus-visible",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-keyboard-trap",
    frameworkId: rgaaFramework.id,
    code: "RGAA 12.9",
    secondaryCode: "WCAG 2.1.2",
    title: "Keyboard focus is not trapped",
    description:
      "Users can Tab away from every widget except intentional modal dialogs.",
    checkId: "keyboard-trap",
    complianceWeight: 1.5,
  },
  {
    id: "ctl-focus-not-obscured",
    frameworkId: rgaaFramework.id,
    code: "WCAG 2.4.11",
    secondaryCode: "WCAG 2.4.11",
    title: "Focused controls are not hidden by other content",
    description:
      "Sticky headers, banners, and overlays do not fully cover the focused control.",
    checkId: "focus-not-obscured",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-focus-not-obscured-enhanced",
    frameworkId: rgaaFramework.id,
    code: "WCAG 2.4.12",
    secondaryCode: "WCAG 2.4.12",
    title: "No part of the focused control is hidden",
    description:
      "Sticky headers, banners, and overlays must not cover any portion of the focused control.",
    checkId: "focus-not-obscured-enhanced",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-focus-appearance",
    frameworkId: rgaaFramework.id,
    code: "WCAG 2.4.13",
    secondaryCode: "WCAG 2.4.13",
    title: "Focus indicator meets minimum size",
    description:
      "The focus indicator is large enough to be visible when keyboard navigating.",
    checkId: "focus-appearance",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-identical-links-purpose",
    frameworkId: rgaaFramework.id,
    code: "WCAG 2.4.9",
    secondaryCode: "WCAG 2.4.9",
    title: "Links with the same name serve the same purpose",
    description:
      "When multiple links share an accessible name, they should lead to the same destination or equivalent action.",
    checkId: "identical-links-purpose",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-accessible-auth",
    frameworkId: rgaaFramework.id,
    code: "WCAG 3.3.8",
    secondaryCode: "WCAG 3.3.8",
    title: "Authentication does not block autofill or paste",
    description:
      "Login and credential fields allow autocomplete and paste so password managers work.",
    checkId: "accessible-auth",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-dragging",
    frameworkId: rgaaFramework.id,
    code: "WCAG 2.5.7",
    secondaryCode: "WCAG 2.5.7",
    title: "Drag operations have a single-pointer alternative",
    description:
      "Drag-and-drop interactions also expose buttons or inputs for users who cannot drag.",
    checkId: "dragging",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-new-window-onload",
    frameworkId: rgaaFramework.id,
    code: "RGAA 13.2",
    secondaryCode: "WCAG 3.2.5",
    title: "No unsolicited windows on page load",
    description:
      "New windows or tabs open only from an explicit user action, not on mount.",
    checkId: "new-window-onload",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-dir-change",
    frameworkId: rgaaFramework.id,
    code: "RGAA 8.10",
    secondaryCode: "WCAG 1.3.2",
    title: "Text direction changes are marked",
    description:
      "Mixed right-to-left and left-to-right passages declare dir on the changing node.",
    checkId: "dir-change",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-blockquote-cite",
    frameworkId: rgaaFramework.id,
    code: "RGAA 9.4",
    secondaryCode: "WCAG 1.3.1",
    title: "Block quotes with a cite expose citation text",
    description:
      "When blockquote cites a source URL, citation text is available to assistive technologies.",
    checkId: "blockquote-cite",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-outline-none",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.7",
    secondaryCode: "WCAG 2.4.7",
    title: "Focus styles are not removed without a replacement",
    description:
      "outline-none or equivalent is paired with a visible focus-visible style in source.",
    checkId: "outline-none",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-status-live",
    frameworkId: rgaaFramework.id,
    code: "RGAA 7.5",
    secondaryCode: "WCAG 4.1.3",
    title: "Status messages use live regions",
    description:
      "Validation and toast feedback is exposed through role=status, role=alert, or aria-live.",
    checkId: "status-live",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-non-text-contrast",
    frameworkId: rgaaFramework.id,
    code: "RGAA 3.3",
    secondaryCode: "WCAG 1.4.11",
    title: "Non-text UI has sufficient contrast",
    description:
      "Borders, icons, and focus indicators meet 3:1 contrast against adjacent colors.",
    checkId: "non-text-contrast",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-reflow",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.11",
    secondaryCode: "WCAG 1.4.10",
    title: "Content reflows at 320 CSS pixels",
    description:
      "No horizontal scrolling is required at 320px width except for data tables and maps.",
    checkId: "reflow",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-text-spacing-runtime",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.12",
    secondaryCode: "WCAG 1.4.12",
    title: "Text survives WCAG spacing overrides",
    description:
      "Content is not clipped when users apply WCAG 1.4.12 text-spacing styles.",
    checkId: "text-spacing-runtime",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-hover-content",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.13",
    secondaryCode: "WCAG 1.4.13",
    title: "Hover and focus content is keyboard reachable",
    description:
      "Content shown on hover or focus can be dismissed, hovered, and reached by keyboard.",
    checkId: "hover-content",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-label-adjacent",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.4",
    secondaryCode: "WCAG 3.3.2",
    title: "Labels are visually adjacent to fields",
    description:
      "Programmatic labels appear next to the controls they name, not far away on the page.",
    checkId: "label-adjacent",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-both-colors",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.5",
    secondaryCode: "WCAG 1.4.3",
    title: "Foreground and background colors are paired",
    description:
      "Text containers set both color and background-color so user stylesheets do not break contrast.",
    checkId: "both-colors",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-redundant-entry",
    frameworkId: rgaaFramework.id,
    code: "WCAG 3.3.7",
    secondaryCode: "WCAG 3.3.7",
    title: "Multi-step forms do not re-ask known data",
    description:
      "Information collected earlier in a flow is reused instead of requested again without cause.",
    checkId: "redundant-entry",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-css-disabled-content",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.2",
    secondaryCode: "WCAG 1.3.1",
    title: "Essential content is not CSS-only",
    description:
      "Information is available when author stylesheets are disabled; text is not conveyed only through CSS content or background images.",
    checkId: "css-disabled-content",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-media-keyboard",
    frameworkId: rgaaFramework.id,
    code: "RGAA 4.11",
    secondaryCode: "WCAG 2.1.1",
    title: "Rendered media controls respond to keyboard",
    description:
      "Native video and audio controls on the rendered page can be focused and operated with the keyboard.",
    checkId: "media-keyboard",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-multiple-ways",
    frameworkId: rgaaFramework.id,
    code: "RGAA 12.1",
    secondaryCode: "WCAG 2.4.5",
    title: "Multiple ways to find pages",
    description:
      "Users can reach pages through at least two mechanisms such as navigation, search, or a sitemap.",
    checkId: "multiple-ways",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-consistent-nav",
    frameworkId: rgaaFramework.id,
    code: "RGAA 12.2",
    secondaryCode: "WCAG 3.2.3",
    title: "Navigation is consistent across pages",
    description:
      "Primary navigation appears in the same order and relative position on each configured preview route.",
    checkId: "consistent-nav",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-consistent-labels",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.3",
    secondaryCode: "WCAG 3.2.4",
    title: "Same-purpose fields use consistent labels",
    description:
      "Fields with the same name or autocomplete token use the same accessible label on every configured route.",
    checkId: "consistent-labels",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-sitemap-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 12.3",
    secondaryCode: "WCAG 2.4.5",
    title: "Sitemap entries are pertinent",
    description:
      "When a sitemap is provided, its entries accurately describe the pages they link to.",
    checkId: null,
    complianceWeight: 1.1,
  },
  {
    id: "ctl-search-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 12.4",
    secondaryCode: "WCAG 2.4.5",
    title: "Sitemap is reached the same way on every page",
    description:
      "The sitemap entry point appears in the same relative position on every page in the set.",
    checkId: "consistent-sitemap",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-nav-mechanisms-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 12.5",
    secondaryCode: "WCAG 2.4.5",
    title: "Search is reached the same way on every page",
    description:
      "The search control appears in the same relative position on every page in the set.",
    checkId: "consistent-search",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-landmark-regions-consistent",
    frameworkId: rgaaFramework.id,
    code: "RGAA 12.6",
    secondaryCode: "WCAG 1.3.1",
    title: "Landmark regions are consistent across pages",
    description:
      "Header, main, and other landmark regions are present on every route when they appear on any route in the set.",
    checkId: "consistent-landmarks",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-consistent-help",
    frameworkId: rgaaFramework.id,
    code: "WCAG 3.2.6",
    secondaryCode: "WCAG 3.2.6",
    title: "Help mechanisms appear in a consistent order",
    description:
      "Contact, help, and support entry points appear in the same relative order on every page.",
    checkId: "consistent-help",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-captcha-alt",
    frameworkId: rgaaFramework.id,
    code: "RGAA 1.4",
    secondaryCode: "WCAG 1.1.1",
    title: "CAPTCHA alternatives identify their function",
    description:
      "Test or CAPTCHA images expose an alternative that identifies their purpose.",
    checkId: null,
    complianceWeight: 1.2,
  },
  {
    id: "ctl-image-description-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 1.7",
    secondaryCode: "WCAG 1.1.1",
    title: "Detailed image descriptions are pertinent",
    description:
      "Long descriptions for complex images are accurate and complete.",
    checkId: null,
    complianceWeight: 1.2,
  },
  {
    id: "ctl-transcript-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 4.2",
    secondaryCode: "WCAG 1.2.1",
    title: "Transcripts and audio descriptions are pertinent",
    description:
      "Text alternatives for audio and video match the media content.",
    checkId: null,
    complianceWeight: 1.3,
  },
  {
    id: "ctl-audio-description",
    frameworkId: rgaaFramework.id,
    code: "RGAA 4.5",
    secondaryCode: "WCAG 1.2.5",
    title: "Synchronized audio description is provided when needed",
    description:
      "Pre-recorded video with visual information not in the soundtrack includes audio description.",
    checkId: "audio-description-track",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-media-identification",
    frameworkId: rgaaFramework.id,
    code: "RGAA 4.7",
    secondaryCode: "WCAG 1.1.1",
    title: "Media is identified and has alternatives",
    description:
      "Non-temporal media is identified and has a text alternative when needed.",
    checkId: "media-identification",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-table-summary-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 5.2",
    secondaryCode: "WCAG 1.3.1",
    title: "Table summaries are pertinent",
    description:
      "Complex table summaries accurately describe structure and relationships.",
    checkId: null,
    complianceWeight: 1.1,
  },
  {
    id: "ctl-layout-table-linearization",
    frameworkId: rgaaFramework.id,
    code: "RGAA 5.3",
    secondaryCode: "WCAG 1.3.2",
    title: "Layout tables linearize sensibly",
    description:
      "When CSS is disabled, layout tables still produce a meaningful reading order.",
    checkId: "layout-table-linearization",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-table-title-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 5.5",
    secondaryCode: "WCAG 1.3.1",
    title: "Table titles are pertinent",
    description:
      "Table captions and titles describe the table content accurately.",
    checkId: null,
    complianceWeight: 1.1,
  },
  {
    id: "ctl-script-alternative-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 7.2",
    secondaryCode: "WCAG 4.1.2",
    title: "Script alternatives are pertinent",
    description:
      "Alternatives to scripted content convey the same information.",
    checkId: null,
    complianceWeight: 1.1,
  },
  {
    id: "ctl-hidden-content-ignored",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.8",
    secondaryCode: "WCAG 4.1.2",
    title: "Hidden content is meant to be ignored",
    description:
      "Content hidden from sighted users is also hidden from assistive technology.",
    checkId: "hidden-content",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-sensory-rule-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.10",
    secondaryCode: "WCAG 1.3.3",
    title: "Sensory instructions are implemented pertinently",
    description:
      "Instructions that avoid sensory-only cues are accurate and sufficient.",
    checkId: null,
    complianceWeight: 1.0,
  },
  {
    id: "ctl-legend-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.7",
    secondaryCode: "WCAG 1.3.1",
    title: "Fieldset legends are pertinent",
    description:
      "Each fieldset legend describes the group of controls it labels.",
    checkId: null,
    complianceWeight: 1.1,
  },
  {
    id: "ctl-button-name-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.9",
    secondaryCode: "WCAG 4.1.2",
    title: "Button names are pertinent",
    description:
      "Each button name describes the action it performs in context.",
    checkId: null,
    complianceWeight: 1.2,
  },
  {
    id: "ctl-validation-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.10",
    secondaryCode: "WCAG 3.3.1",
    title: "Validation is used pertinently",
    description:
      "Client-side validation rules match business requirements and help users recover.",
    checkId: null,
    complianceWeight: 1.1,
  },
  {
    id: "ctl-office-docs-alt",
    frameworkId: rgaaFramework.id,
    code: "RGAA 13.3",
    secondaryCode: "WCAG 1.1.1",
    title: "Office documents have accessible alternatives",
    description:
      "Downloadable office documents have an accessible HTML or text alternative.",
    checkId: null,
    complianceWeight: 1.1,
  },
  {
    id: "ctl-office-docs-alt-present",
    frameworkId: rgaaFramework.id,
    code: "RGAA 13.3",
    secondaryCode: "WCAG 1.1.1",
    title: "Office documents have an accessible alternative link",
    description:
      "Downloadable office documents have an adjacent HTML or text alternative link.",
    checkId: "office-docs-alt-present",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-flash-threshold",
    frameworkId: rgaaFramework.id,
    code: "RGAA 13.7",
    secondaryCode: "WCAG 2.3.1",
    title: "Flashes are below threshold",
    description:
      "Content does not flash more than three times per second above luminance thresholds.",
    checkId: "flash-threshold",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-media-keyboard-static",
    frameworkId: rgaaFramework.id,
    code: "RGAA 4.12",
    secondaryCode: "WCAG 2.1.1",
    title: "Non-temporal media is keyboard operable",
    description:
      "Embedded documents and objects can be operated from the keyboard.",
    checkId: "media-keyboard-static",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-img-alt-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 1.3",
    secondaryCode: "WCAG 1.1.1",
    title: "Image text alternatives are pertinent",
    description:
      "Each informative image's text alternative describes its purpose in context. Presence of alt is a separate control.",
    checkId: null,
    complianceWeight: 1.4,
  },
  {
    id: "ctl-decorative-ignored",
    frameworkId: rgaaFramework.id,
    code: "RGAA 1.2",
    secondaryCode: "WCAG 1.1.1",
    title: "Decorative images are ignored by assistive technology",
    description:
      "Decorative images use empty alt or a presentation role so they are not announced.",
    checkId: "decorative-ignored",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-frame-title-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 2.2",
    secondaryCode: "WCAG 4.1.2",
    title: "Frame titles are pertinent",
    description:
      "Each iframe title describes the embedded content; generic titles like “frame” fail.",
    checkId: null,
    complianceWeight: 1.2,
  },
  {
    id: "ctl-page-title-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 8.6",
    secondaryCode: "WCAG 2.4.2",
    title: "Page titles are pertinent",
    description:
      "The document title identifies the page uniquely in context (not a repeated “Home” on every route).",
    checkId: null,
    complianceWeight: 1.3,
  },
  {
    id: "ctl-page-title-unique",
    frameworkId: rgaaFramework.id,
    code: "RGAA 8.6",
    secondaryCode: "WCAG 2.4.2",
    title: "Page titles are unique across routes",
    description:
      "Document titles differ across preview routes. Identical titles on every page fail pertinence (RGAA 8.6).",
    checkId: "duplicate-page-title",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-link-explicit",
    frameworkId: rgaaFramework.id,
    code: "RGAA 6.1",
    secondaryCode: "WCAG 2.4.4",
    title: "Link purpose is explicit",
    description:
      "Each link's accessible name makes sense out of context (not “click here” or “read more” alone).",
    checkId: "link-explicit-heuristic",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-label-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.2",
    secondaryCode: "WCAG 3.3.2",
    title: "Form labels are pertinent",
    description:
      "Each field label describes what to enter; generic labels like “input” fail.",
    checkId: null,
    complianceWeight: 1.3,
  },
  {
    id: "ctl-captions-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 4.4",
    secondaryCode: "WCAG 1.2.2",
    title: "Captions are pertinent",
    description:
      "When captions exist, they match the spoken audio and identify speakers when needed.",
    checkId: null,
    complianceWeight: 1.3,
  },
  {
    id: "ctl-focus-order-logical",
    frameworkId: rgaaFramework.id,
    code: "RGAA 12.8",
    secondaryCode: "WCAG 2.4.3",
    title: "Focus order matches the visual reading order",
    description:
      "Keyboard focus moves in a sequence that preserves meaning; CSS order must not invert the DOM order without cause.",
    checkId: "focus-order-logical",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-error-prevention",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.12",
    secondaryCode: "WCAG 3.3.4",
    title: "Legal and financial submissions can be reviewed or reversed",
    description:
      "Forms that change legal, financial, or test data let the user check, confirm, or reverse the submission.",
    checkId: "error-prevention",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-supplementary-content-keyboard",
    frameworkId: rgaaFramework.id,
    code: "RGAA 12.11",
    secondaryCode: "WCAG 2.1.1",
    title: "Supplementary content on hover or focus is keyboard reachable",
    description:
      "Content shown on hover, focus, or activation is reachable and operable from the keyboard when needed.",
    checkId: "supplementary-content-keyboard",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-captcha-alternative",
    frameworkId: rgaaFramework.id,
    code: "RGAA 1.5",
    secondaryCode: "WCAG 1.1.1",
    title: "CAPTCHA has a non-image alternative",
    description:
      "When an image CAPTCHA is used, a different modality (audio, logic question, or human contact) provides the same function.",
    checkId: "captcha-alternative",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-audio-description-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 4.6",
    secondaryCode: "WCAG 1.2.5",
    title: "Audio description is pertinent",
    description:
      "When audio description is provided, it matches the visual information that is not in the soundtrack.",
    checkId: null,
    complianceWeight: 1.2,
  },
  {
    id: "ctl-nontemporal-media-alt",
    frameworkId: rgaaFramework.id,
    code: "RGAA 4.8",
    secondaryCode: "WCAG 1.1.1",
    title: "Non-temporal media has a text alternative",
    description:
      "Object, embed, and canvas media that is not time-based expose a name or an adjacent alternative.",
    checkId: "nontemporal-media-alt",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-nontemporal-media-alt-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 4.9",
    secondaryCode: "WCAG 1.1.1",
    title: "Non-temporal media alternatives are pertinent",
    description:
      "Text alternatives for object, embed, and canvas media describe the content accurately.",
    checkId: null,
    complianceWeight: 1.1,
  },
  {
    id: "ctl-media-at-compatible",
    frameworkId: rgaaFramework.id,
    code: "RGAA 4.13",
    secondaryCode: "WCAG 4.1.2",
    title: "Media players are compatible with assistive technology",
    description:
      "Temporal and non-temporal media expose name, role, and value to assistive technology.",
    checkId: "media-at-compatible",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-lang-change-indicated",
    frameworkId: rgaaFramework.id,
    code: "RGAA 8.7",
    secondaryCode: "WCAG 3.1.2",
    title: "Language changes are indicated in the source",
    description:
      "Passages in a language different from the page default set lang on the containing element.",
    checkId: "lang-change",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-css-for-presentation",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.1",
    secondaryCode: "WCAG 1.3.1",
    title: "Presentation is controlled with CSS, not markup",
    description:
      "Layout and visual formatting use stylesheets rather than deprecated presentational markup.",
    checkId: "css-for-presentation",
    complianceWeight: 1.0,
  },
  {
    id: "ctl-css-off-understandable",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.3",
    secondaryCode: "WCAG 1.3.2",
    title: "Content remains understandable with CSS disabled",
    description:
      "Reading order and meaning are preserved when stylesheets are disabled.",
    checkId: "css-off-understandable",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-info-not-color-only",
    frameworkId: rgaaFramework.id,
    code: "RGAA 3.1",
    secondaryCode: "WCAG 1.4.1",
    title: "Information is not conveyed by color alone",
    description:
      "Charts, required fields, and status are identifiable without perceiving color. Link underline is a separate control (10.6).",
    checkId: "info-not-color-only",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-css-hover-keyboard",
    frameworkId: rgaaFramework.id,
    code: "RGAA 10.14",
    secondaryCode: "WCAG 2.1.1",
    title: "CSS-only extra content is available from the keyboard",
    description:
      "Content shown only via :hover or :focus CSS can also be revealed with keyboard focus.",
    checkId: "css-hover-keyboard",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-field-grouping",
    frameworkId: rgaaFramework.id,
    code: "RGAA 11.5",
    secondaryCode: "WCAG 1.3.1",
    title: "Related fields are grouped when needed",
    description:
      "Radio groups, related checkboxes, and identity field clusters are wrapped in a fieldset or labelled group.",
    checkId: "field-grouping",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-office-docs-equivalent",
    frameworkId: rgaaFramework.id,
    code: "RGAA 13.4",
    secondaryCode: "WCAG 1.1.1",
    title: "Accessible office alternatives are equivalent",
    description:
      "HTML or text alternatives to downloadable office files carry the same information.",
    checkId: null,
    complianceWeight: 1.1,
  },
  {
    id: "ctl-cryptic-content-alt",
    frameworkId: rgaaFramework.id,
    code: "RGAA 13.5",
    secondaryCode: "WCAG 1.1.1",
    title: "Cryptic content has a text alternative",
    description:
      "ASCII art, emoticon clusters, and similar cryptic text have an accessible alternative.",
    checkId: "cryptic-content-alt",
    complianceWeight: 1.0,
  },
  {
    id: "ctl-cryptic-content-alt-relevant",
    frameworkId: rgaaFramework.id,
    code: "RGAA 13.6",
    secondaryCode: "WCAG 1.1.1",
    title: "Cryptic-content alternatives are pertinent",
    description:
      "Alternatives for cryptic content convey the intended meaning.",
    checkId: null,
    complianceWeight: 1.0,
  },
  {
    id: "ctl-captions-live",
    frameworkId: rgaaFramework.id,
    code: "WCAG 1.2.4",
    secondaryCode: "WCAG 1.2.4",
    title: "Live synchronized media has captions",
    description:
      "When live audio is part of synchronized media, captions are provided.",
    checkId: "captions-live",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-accessible-auth-enhanced",
    frameworkId: rgaaFramework.id,
    code: "WCAG 3.3.9",
    secondaryCode: "WCAG 3.3.9",
    title: "Authentication avoids object-recognition puzzles",
    description:
      "Login and credential steps do not require image-selection or object-recognition CAPTCHA without an allowed alternative.",
    checkId: "accessible-auth-enhanced",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-color-contrast-enhanced",
    frameworkId: rgaaFramework.id,
    code: "WCAG 1.4.6",
    secondaryCode: "WCAG 1.4.6",
    title: "Text contrast meets 7:1 (enhanced)",
    description:
      "Foreground and background color of text meets WCAG AAA contrast on the rendered page.",
    checkId: "color-contrast-enhanced",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-reduced-motion",
    frameworkId: rgaaFramework.id,
    code: "WCAG 2.3.3",
    secondaryCode: "WCAG 2.3.3",
    title: "Interaction animations respect reduced motion",
    description:
      "Motion from interactions can be disabled through prefers-reduced-motion or an equivalent alternative.",
    checkId: "reduced-motion",
    complianceWeight: 1.0,
  },
  {
    id: "ctl-audio-description-or-alt",
    frameworkId: rgaaFramework.id,
    code: "WCAG 1.2.3",
    secondaryCode: "WCAG 1.2.3",
    title: "Prerecorded video has audio description or a media alternative",
    description:
      "Video with visual information not in the soundtrack has audio description or a full text alternative (A).",
    checkId: "audio-description-or-alt",
    complianceWeight: 1.3,
  },
];