import { rgaaControls, rgaaFramework } from "./controls";
import type { FrameworkPreset } from "@/adapters/types";

export type { FrameworkPreset };

/** Framework + level targets for RGAA assessment. */
export const rgaaPresets: FrameworkPreset[] = [
  {
    id: "preset-rgaa-full",
    name: "Full RGAA 4",
    description: "Every machine-checkable control from RGAA 4",
    frameworkId: rgaaFramework.id,
    controlIds: rgaaControls.map((control) => control.id),
  },
  {
    id: "preset-rgaa-aa",
    name: "RGAA 4 AA",
    description: "Core RGAA 4 AA success criteria",
    frameworkId: rgaaFramework.id,
    controlIds: [
      "ctl-img-alt",
      "ctl-button-name",
      "ctl-link-name",
      "ctl-html-lang",
      "ctl-focus-order",
      "ctl-input-label",
      "ctl-heading-order",
      "ctl-empty-heading",
      "ctl-iframe-title",
      "ctl-autoplay-media",
      "ctl-duplicate-id",
      "ctl-form-error-association",
      "ctl-aria-hidden-focusable",
      "ctl-aria-role",
      "ctl-aria-props",
      "ctl-aria-required-attr",
      "ctl-no-autofocus",
      "ctl-keyboard-interaction",
      "ctl-color-contrast",
      "ctl-document-title",
      "ctl-bypass",
      "ctl-landmark-one-main",
      "ctl-nested-interactive",
      "ctl-target-size",
      "ctl-meta-viewport",
      "ctl-list-structure",
      "ctl-autocomplete-valid",
      "ctl-table-headers",
      "ctl-page-heading",
      "ctl-content-region",
      "ctl-label-in-name",
      "ctl-lang-parts",
      "ctl-aria-roledescription",
      "ctl-presentation-role",
      "ctl-no-auto-refresh",
      "ctl-no-orientation-lock",
    ],
  },
  {
    id: "preset-rgaa-aaa",
    name: "RGAA 4 AAA",
    description: "Enhanced RGAA 4 AAA success criteria",
    frameworkId: rgaaFramework.id,
    controlIds: [
      "ctl-img-alt",
      "ctl-button-name",
      "ctl-link-name",
      "ctl-html-lang",
      "ctl-focus-order",
      "ctl-input-label",
      "ctl-heading-order",
      "ctl-empty-heading",
      "ctl-iframe-title",
      "ctl-autoplay-media",
      "ctl-duplicate-id",
      "ctl-form-error-association",
      "ctl-aria-hidden-focusable",
      "ctl-aria-role",
      "ctl-aria-props",
      "ctl-aria-required-attr",
      "ctl-no-autofocus",
      "ctl-keyboard-interaction",
      "ctl-color-contrast",
      "ctl-document-title",
      "ctl-bypass",
      "ctl-landmark-one-main",
      "ctl-nested-interactive",
      "ctl-target-size",
      "ctl-meta-viewport",
      "ctl-list-structure",
      "ctl-autocomplete-valid",
      "ctl-table-headers",
      "ctl-page-heading",
      "ctl-content-region",
      "ctl-label-in-name",
      "ctl-lang-parts",
      "ctl-aria-roledescription",
      "ctl-presentation-role",
      "ctl-no-auto-refresh",
      "ctl-no-orientation-lock",
      "ctl-pointer-gesture",
      "ctl-pointer-cancellation",
      "ctl-motion-actuation",
      "ctl-focus-context-change",
      "ctl-input-context-change",
      "ctl-sensory-characteristics",
      "ctl-image-of-text",
      "ctl-error-suggestion",
    ],
  },
];