import type { Control, Framework } from "@/core/project-types";

export const wcagFramework: Framework = {
  id: "fw-wcag-2-1",
  name: "WCAG 2.1 (accessibility standard)",
  version: "2026.3",
};

export const wcagControls: Control[] = [
  {
    id: "ctl-img-alt",
    frameworkId: wcagFramework.id,
    code: "WCAG 1.1.1",
    secondaryCode: "RGAA 1.1",
    title: "Images have a text alternative",
    description:
      "Every informative image exposes a text alternative; decorative images are explicitly marked as such.",
    checkId: "img-alt",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-button-name",
    frameworkId: wcagFramework.id,
    code: "WCAG 4.1.2",
    secondaryCode: "RGAA 11.9",
    title: "Buttons have an accessible name",
    description:
      "Every button exposes a name describing its action, via text content or an ARIA label.",
    checkId: "button-name",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-link-name",
    frameworkId: wcagFramework.id,
    code: "WCAG 2.4.4",
    secondaryCode: "RGAA 6.1",
    title: "Links have an accessible name",
    description:
      "Every link exposes a name describing its destination, via text content, image alternatives, or an ARIA label.",
    checkId: "anchor-name",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-html-lang",
    frameworkId: wcagFramework.id,
    code: "WCAG 3.1.1",
    secondaryCode: "RGAA 8.3",
    title: "The page declares its language",
    description:
      "The document's default human language is programmatically determinable via the lang attribute.",
    checkId: "html-lang",
    complianceWeight: 1.5,
  },
  {
    id: "ctl-focus-order",
    frameworkId: wcagFramework.id,
    code: "WCAG 2.4.3",
    secondaryCode: "RGAA 12.8",
    title: "Focus order is logical",
    description:
      "Keyboard focus follows the natural document order; no element forces a custom order with a positive tabindex.",
    checkId: "positive-tabindex",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-input-label",
    frameworkId: wcagFramework.id,
    code: "WCAG 3.3.2",
    secondaryCode: "RGAA 11.1",
    title: "Form fields have labels",
    description:
      "Every form field exposes a label telling users what to enter, via <label> association or ARIA attributes.",
    checkId: "input-label",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-heading-order",
    frameworkId: wcagFramework.id,
    code: "WCAG 1.3.1",
    secondaryCode: "RGAA 9.1",
    title: "Heading levels follow a logical order",
    description:
      "Headings do not skip levels in the document outline (e.g. h2 must not jump to h4).",
    checkId: "heading-order",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-empty-heading",
    frameworkId: wcagFramework.id,
    code: "WCAG 1.3.1",
    secondaryCode: "RGAA 9.2",
    title: "Headings have accessible names",
    description:
      "Every heading exposes text or an ARIA name so the outline is usable.",
    checkId: "empty-heading",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-iframe-title",
    frameworkId: wcagFramework.id,
    code: "WCAG 4.1.2",
    secondaryCode: "RGAA 2.1",
    title: "Frames have a title",
    description:
      "Every iframe exposes a title describing its purpose to assistive technologies.",
    checkId: "iframe-title",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-autoplay-media",
    frameworkId: wcagFramework.id,
    code: "WCAG 1.4.2",
    secondaryCode: "RGAA 4.1",
    title: "Media does not autoplay",
    description:
      "Audio and video do not start automatically; users control playback.",
    checkId: "autoplay-media",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-duplicate-id",
    frameworkId: wcagFramework.id,
    code: "WCAG 4.1.1",
    secondaryCode: "RGAA 8.2",
    title: "IDs are unique",
    description:
      "id attributes are unique within a document so labels and ARIA references resolve correctly.",
    checkId: "duplicate-id",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-form-error-association",
    frameworkId: wcagFramework.id,
    code: "WCAG 3.3.1",
    secondaryCode: "RGAA 11.10",
    title: "Form errors are associated with fields",
    description:
      "When a field is invalid, its error message is programmatically associated (e.g. aria-describedby).",
    checkId: "form-error-association",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-aria-hidden-focusable",
    frameworkId: wcagFramework.id,
    code: "WCAG 4.1.2",
    secondaryCode: "RGAA 8.9",
    title: "Hidden elements are not focusable",
    description:
      "Elements with aria-hidden must not be reachable by keyboard focus.",
    checkId: "aria-hidden-focusable",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-aria-role",
    frameworkId: wcagFramework.id,
    code: "WCAG 4.1.2",
    secondaryCode: "RGAA 8.6",
    title: "ARIA roles are valid",
    description:
      "role values are concrete ARIA roles, not abstract or invented names.",
    checkId: "aria-role",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-aria-props",
    frameworkId: wcagFramework.id,
    code: "WCAG 4.1.2",
    secondaryCode: "RGAA 8.7",
    title: "ARIA attributes are valid",
    description:
      "aria-* attributes exist in the ARIA specification (no typos or unknown properties).",
    checkId: "aria-props",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-aria-required-attr",
    frameworkId: wcagFramework.id,
    code: "WCAG 4.1.2",
    secondaryCode: "RGAA 8.8",
    title: "Roles include required ARIA properties",
    description:
      "An explicit ARIA role exposes every property that role requires (e.g. checkbox needs aria-checked).",
    checkId: "aria-required-attr",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-no-autofocus",
    frameworkId: wcagFramework.id,
    code: "WCAG 2.4.3",
    secondaryCode: "RGAA 12.7",
    title: "Pages do not steal focus on load",
    description:
      "autoFocus is not used; keyboard and screen reader users keep control of where focus starts.",
    checkId: "no-autofocus",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-keyboard-interaction",
    frameworkId: wcagFramework.id,
    code: "WCAG 2.1.1",
    secondaryCode: "RGAA 12.11",
    title: "Pointer-only controls are also operable by keyboard",
    description:
      "Non-native elements with click or hover handlers are focusable, have an interactive role, and expose equivalent keyboard events.",
    checkId: "keyboard-interaction",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-color-contrast",
    frameworkId: wcagFramework.id,
    code: "WCAG 1.4.3",
    secondaryCode: "RGAA 3.2",
    title: "Text contrast meets 4.5:1",
    description:
      "Foreground and background color of text meets WCAG AA contrast (measured on the rendered page).",
    checkId: "color-contrast",
    complianceWeight: 1.5,
  },
  {
    id: "ctl-document-title",
    frameworkId: wcagFramework.id,
    code: "WCAG 2.4.2",
    secondaryCode: "RGAA 8.5",
    title: "The page has a title",
    description:
      "The rendered document exposes a non-empty <title> describing the page.",
    checkId: "document-title",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-bypass",
    frameworkId: wcagFramework.id,
    code: "WCAG 2.4.1",
    secondaryCode: "RGAA 12.7",
    title: "A mechanism skips repeated blocks",
    description:
      "The page provides a skip link, landmark, or heading structure so keyboard users can bypass repeated chrome.",
    checkId: "bypass",
    complianceWeight: 1.4,
  },
  {
    id: "ctl-landmark-one-main",
    frameworkId: wcagFramework.id,
    code: "WCAG 1.3.1",
    secondaryCode: "RGAA 12.6",
    title: "The page has one main landmark",
    description:
      "The rendered page exposes exactly one main landmark for the primary content.",
    checkId: "landmark-one-main",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-nested-interactive",
    frameworkId: wcagFramework.id,
    code: "WCAG 4.1.2",
    secondaryCode: "RGAA 8.9",
    title: "Interactive controls are not nested",
    description:
      "Buttons, links, and other widgets are not placed inside other widgets (measured on the rendered tree).",
    checkId: "nested-interactive",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-target-size",
    frameworkId: wcagFramework.id,
    code: "WCAG 2.5.8",
    secondaryCode: "RGAA 11.11",
    title: "Pointer targets are large enough",
    description:
      "Interactive targets meet the WCAG 2.2 minimum size (24×24 CSS pixels) on the rendered page.",
    checkId: "target-size",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-meta-viewport",
    frameworkId: wcagFramework.id,
    code: "WCAG 1.4.4",
    secondaryCode: "RGAA 10.4",
    title: "Viewport allows zoom",
    description:
      "The viewport meta tag must not disable zooming (no user-scalable=no or maximum-scale below 2).",
    checkId: "meta-viewport",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-list-structure",
    frameworkId: wcagFramework.id,
    code: "WCAG 1.3.1",
    secondaryCode: "RGAA 9.3",
    title: "Lists use correct structure",
    description:
      "List items are children of ul/ol/menu, and list containers only contain li children.",
    checkId: "list-structure",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-autocomplete-valid",
    frameworkId: wcagFramework.id,
    code: "WCAG 1.3.5",
    secondaryCode: "RGAA 11.13",
    title: "Autocomplete tokens are valid",
    description:
      "Form controls that declare autocomplete use valid HTML autofill tokens so browsers and ATs can identify the expected input purpose.",
    checkId: "autocomplete-valid",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-table-headers",
    frameworkId: wcagFramework.id,
    code: "WCAG 1.3.1",
    secondaryCode: "RGAA 5.2",
    title: "Table data cells have headers",
    description:
      "Every data cell in a data table is associated with one or more header cells (th/id or scope) so the relationship is programmatically determinable.",
    checkId: "table-headers",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-page-heading",
    frameworkId: wcagFramework.id,
    code: "WCAG 2.4.6",
    secondaryCode: "RGAA 9.2",
    title: "The page has a top-level heading",
    description:
      "Each page exposes at least one heading (h1) so its structure is perceivable to assistive technology.",
    checkId: "page-heading",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-content-region",
    frameworkId: wcagFramework.id,
    code: "WCAG 1.3.1",
    secondaryCode: "RGAA 9.2.1",
    title: "Page content sits inside landmarks",
    description:
      "All page content is contained within landmark regions (header, nav, main, aside, footer) so its structure is conveyed to assistive technology.",
    checkId: "content-region",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-label-in-name",
    frameworkId: wcagFramework.id,
    code: "WCAG 2.5.3",
    secondaryCode: "RGAA 11.1",
    title: "Visible label is contained in the accessible name",
    description:
      "For components with a visible text label, the accessible name includes that visible label (punctuation and letter-case ignored).",
    checkId: "label-in-name",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-lang-parts",
    frameworkId: wcagFramework.id,
    code: "WCAG 3.1.2",
    secondaryCode: "RGAA 8.8",
    title: "Language of parts is declared",
    description:
      "Any block of text in a language different from the page default declares its language via a lang attribute.",
    checkId: "lang-parts",
    complianceWeight: 1.3,
  },
  {
    id: "ctl-aria-roledescription",
    frameworkId: wcagFramework.id,
    code: "WCAG 4.1.2",
    secondaryCode: "RGAA 7.1",
    title: "aria-roledescription values are valid",
    description:
      "Elements that use aria-roledescription provide a non-empty, meaningful value that does not duplicate the implicit role name.",
    checkId: "aria-roledescription",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-presentation-role",
    frameworkId: wcagFramework.id,
    code: "WCAG 4.1.2",
    secondaryCode: "RGAA 8.9",
    title: "Presentation role does not hide focusable content",
    description:
      "Elements with role='presentation' or role='none' do not contain focusable descendants that would become inaccessible.",
    checkId: "presentation-role",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-no-auto-refresh",
    frameworkId: wcagFramework.id,
    code: "WCAG 2.2.1",
    secondaryCode: "RGAA 13.2",
    title: "No unexpected time limits or redirects",
    description:
      "The page does not auto-refresh or redirect after a time limit without user control (meta refresh is removed).",
    checkId: "no-auto-refresh",
    complianceWeight: 1.2,
  },
  {
    id: "ctl-no-orientation-lock",
    frameworkId: wcagFramework.id,
    code: "WCAG 1.3.4",
    secondaryCode: "RGAA 13.9.1",
    title: "Content is not restricted to one display orientation",
    description:
      "Content does not lock to portrait or landscape; it adapts to the orientation the user prefers (unless an orientation is essential).",
    checkId: "no-orientation-lock",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-landmark-unique",
    frameworkId: wcagFramework.id,
    code: "WCAG 1.3.1",
    secondaryCode: "RGAA 12.6",
    title: "Landmarks have unique, descriptive names",
    description:
      "When more than one landmark of the same type is used (e.g. multiple nav), each has a distinct accessible name so users can tell them apart.",
    checkId: "landmark-unique",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-pointer-gesture",
    frameworkId: wcagFramework.id,
    code: "WCAG 2.5.1",
    secondaryCode: "RGAA 11.6",
    title: "Pointer gestures have a keyboard alternative",
    description:
      "Functionality operated through a path-based pointer gesture (drag, swipe) also works with a single-pointer or keyboard action.",
    checkId: "pointer-gesture",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-pointer-cancellation",
    frameworkId: wcagFramework.id,
    code: "WCAG 2.5.2",
    secondaryCode: "RGAA 11.7",
    title: "Pointer actions are abortable",
    description:
      "A pointerdown that starts an action provides a pointercancel/up path so the action can be aborted before completion.",
    checkId: "pointer-cancellation",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-motion-actuation",
    frameworkId: wcagFramework.id,
    code: "WCAG 2.5.4",
    secondaryCode: "RGAA 11.8",
    title: "Motion actuation has a non-motion alternative",
    description:
      "Functions triggered by device motion or orientation (shake, tilt) can also be operated without the motion (button/keyboard).",
    checkId: "motion-actuation",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-focus-context-change",
    frameworkId: wcagFramework.id,
    code: "WCAG 3.2.1",
    secondaryCode: "RGAA 10.9",
    title: "Focus does not change context",
    description:
      "Receiving focus does not unexpectedly change context (navigate, submit, open a dialog) without warning.",
    checkId: "focus-context-change",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-input-context-change",
    frameworkId: wcagFramework.id,
    code: "WCAG 3.2.2",
    secondaryCode: "RGAA 10.10",
    title: "Input does not change context",
    description:
      "Changing or entering input does not unexpectedly change context (navigate, submit) without warning or a confirmation step.",
    checkId: "input-context-change",
    complianceWeight: 1.1,
  },
  {
    id: "ctl-sensory-characteristics",
    frameworkId: wcagFramework.id,
    code: "WCAG 1.3.3",
    secondaryCode: "RGAA 10.3",
    title: "Instructions do not rely on sensory characteristics",
    description:
      "Instructions are not conveyed by color, shape, size, sound, or position alone; they are also available as text.",
    checkId: "sensory-characteristics",
    complianceWeight: 1.0,
  },
  {
    id: "ctl-image-of-text",
    frameworkId: wcagFramework.id,
    code: "WCAG 1.4.5",
    secondaryCode: "RGAA 10.1",
    title: "Text is not presented as an image",
    description:
      "Information conveyed as an image of text (CSS background text, role='img' with text) is also available as real text.",
    checkId: "image-of-text",
    complianceWeight: 1.0,
  },
  {
    id: "ctl-error-suggestion",
    frameworkId: wcagFramework.id,
    code: "WCAG 3.3.3",
    secondaryCode: "RGAA 11.12",
    title: "Errors suggest a correction",
    description:
      "When input is invalid, the error identifies the problem and suggests how to fix it (not just that it is wrong).",
    checkId: "error-suggestion",
    complianceWeight: 1.0,
  },
];