import { rgaaControls } from "@/adapters/rgaa/controls";
import { wcagFramework } from "./controls";
import type { FrameworkPreset } from "@/adapters/types";

export type { FrameworkPreset };

/** Framework + level targets for WCAG assessment. */
export const wcagPresets: FrameworkPreset[] = [
  {
    id: "preset-wcag-full",
    name: "Full WCAG 2.1",
    description: "Every catalog control for WCAG (automated and human-reviewed)",
    frameworkId: wcagFramework.id,
    controlIds: rgaaControls.map((control) => control.id),
  },
  {
    id: "preset-wcag-aa",
    name: "WCAG 2.1 AA",
    description: "Core WCAG 2.1 AA success criteria",
    frameworkId: wcagFramework.id,
    controlIds: [
      "ctl-img-alt",
      "ctl-button-name",
      "ctl-link-name",
      "ctl-html-lang",
      "ctl-focus-order",
      "ctl-input-label",
      "ctl-heading-order",
      "ctl-empty-heading",
      "ctl-iframe-title",
      "ctl-autoplay-media",
      "ctl-duplicate-id",
      "ctl-form-error-association",
      "ctl-aria-hidden-focusable",
      "ctl-aria-role",
      "ctl-aria-props",
      "ctl-aria-required-attr",
      "ctl-no-autofocus",
      "ctl-keyboard-interaction",
      "ctl-color-contrast",
      "ctl-document-title",
      "ctl-bypass",
      "ctl-landmark-one-main",
      "ctl-nested-interactive",
      "ctl-target-size",
      "ctl-meta-viewport",
      "ctl-list-structure",
      "ctl-autocomplete-valid",
      "ctl-table-headers",
      "ctl-page-heading",
      "ctl-content-region",
      "ctl-label-in-name",
      "ctl-lang-parts",
      "ctl-aria-roledescription",
      "ctl-presentation-role",
      "ctl-no-auto-refresh",
      "ctl-no-orientation-lock",
      "ctl-video-caption",
      "ctl-audio-caption",
      "ctl-no-blink-marquee",
      "ctl-text-spacing",
      "ctl-use-of-color",
      "ctl-empty-th",
      "ctl-dialog-name",
      "ctl-tab-name",
      "ctl-summary-name",
      "ctl-frame-keyboard",
      "ctl-p-as-heading",
      "ctl-doctype",
      "ctl-fieldset-legend",
      "ctl-autocomplete-purpose",
      "ctl-no-accesskey",
      "ctl-optgroup",
      "ctl-table-caption",
      "ctl-th-scope",
      "ctl-layout-table-markup",
      "ctl-svg-name",
      "ctl-figure-caption",
      "ctl-redundant-role",
      "ctl-noninteractive-tabindex",
      "ctl-aria-activedescendant",
      "ctl-img-alt-relevant",
      "ctl-decorative-ignored",
      "ctl-frame-title-relevant",
      "ctl-page-title-relevant",
      "ctl-link-explicit",
      "ctl-label-relevant",
      "ctl-captions-relevant",
      "ctl-focus-order-logical",
      "ctl-error-prevention",
    ],
  },
  {
    id: "preset-wcag-aaa",
    name: "WCAG 2.1 AAA",
    description: "Enhanced WCAG 2.1 AAA success criteria",
    frameworkId: wcagFramework.id,
    controlIds: [
      "ctl-img-alt",
      "ctl-button-name",
      "ctl-link-name",
      "ctl-html-lang",
      "ctl-focus-order",
      "ctl-input-label",
      "ctl-heading-order",
      "ctl-empty-heading",
      "ctl-iframe-title",
      "ctl-autoplay-media",
      "ctl-duplicate-id",
      "ctl-form-error-association",
      "ctl-aria-hidden-focusable",
      "ctl-aria-role",
      "ctl-aria-props",
      "ctl-aria-required-attr",
      "ctl-no-autofocus",
      "ctl-keyboard-interaction",
      "ctl-color-contrast",
      "ctl-document-title",
      "ctl-bypass",
      "ctl-landmark-one-main",
      "ctl-nested-interactive",
      "ctl-target-size",
      "ctl-meta-viewport",
      "ctl-list-structure",
      "ctl-autocomplete-valid",
      "ctl-table-headers",
      "ctl-page-heading",
      "ctl-content-region",
      "ctl-label-in-name",
      "ctl-lang-parts",
      "ctl-aria-roledescription",
      "ctl-presentation-role",
      "ctl-no-auto-refresh",
      "ctl-no-orientation-lock",
      "ctl-video-caption",
      "ctl-audio-caption",
      "ctl-no-blink-marquee",
      "ctl-text-spacing",
      "ctl-use-of-color",
      "ctl-empty-th",
      "ctl-dialog-name",
      "ctl-tab-name",
      "ctl-summary-name",
      "ctl-frame-keyboard",
      "ctl-p-as-heading",
      "ctl-doctype",
      "ctl-fieldset-legend",
      "ctl-autocomplete-purpose",
      "ctl-no-accesskey",
      "ctl-optgroup",
      "ctl-table-caption",
      "ctl-th-scope",
      "ctl-layout-table-markup",
      "ctl-svg-name",
      "ctl-figure-caption",
      "ctl-redundant-role",
      "ctl-noninteractive-tabindex",
      "ctl-aria-activedescendant",
      "ctl-img-alt-relevant",
      "ctl-decorative-ignored",
      "ctl-frame-title-relevant",
      "ctl-page-title-relevant",
      "ctl-link-explicit",
      "ctl-label-relevant",
      "ctl-captions-relevant",
      "ctl-focus-order-logical",
      "ctl-error-prevention",
      "ctl-pointer-gesture",
      "ctl-pointer-cancellation",
      "ctl-motion-actuation",
      "ctl-focus-context-change",
      "ctl-input-context-change",
      "ctl-sensory-characteristics",
      "ctl-image-of-text",
      "ctl-error-suggestion",
    ],
  },
];