import { rgaaControls } from "@/adapters/rgaa/controls";
import { wcagFramework } from "./controls";
import type { FrameworkPreset } from "@/adapters/types";

export type { FrameworkPreset };

/** Framework + level targets for WCAG assessment. */
export const wcagPresets: FrameworkPreset[] = [
  {
    id: "preset-wcag-full",
    name: "Full WCAG 2.1",
    description: "Every machine-checkable control from WCAG 2.1",
    frameworkId: wcagFramework.id,
    controlIds: rgaaControls.map((control) => control.id),
  },
  {
    id: "preset-wcag-aa",
    name: "WCAG 2.1 AA",
    description: "Core WCAG 2.1 AA success criteria",
    frameworkId: wcagFramework.id,
    controlIds: [
      "ctl-img-alt",
      "ctl-button-name",
      "ctl-link-name",
      "ctl-html-lang",
      "ctl-focus-order",
      "ctl-input-label",
      "ctl-heading-order",
      "ctl-empty-heading",
      "ctl-iframe-title",
      "ctl-autoplay-media",
      "ctl-duplicate-id",
      "ctl-form-error-association",
      "ctl-aria-hidden-focusable",
      "ctl-aria-role",
      "ctl-aria-props",
      "ctl-aria-required-attr",
      "ctl-no-autofocus",
      "ctl-keyboard-interaction",
      "ctl-color-contrast",
      "ctl-document-title",
      "ctl-bypass",
      "ctl-landmark-one-main",
      "ctl-nested-interactive",
      "ctl-target-size",
      "ctl-meta-viewport",
      "ctl-list-structure",
      "ctl-autocomplete-valid",
      "ctl-table-headers",
      "ctl-page-heading",
      "ctl-content-region",
      "ctl-label-in-name",
      "ctl-lang-parts",
      "ctl-aria-roledescription",
      "ctl-presentation-role",
      "ctl-no-auto-refresh",
      "ctl-no-orientation-lock",
    ],
  },
  {
    id: "preset-wcag-aaa",
    name: "WCAG 2.1 AAA",
    description: "Enhanced WCAG 2.1 AAA success criteria",
    frameworkId: wcagFramework.id,
    controlIds: [
      "ctl-img-alt",
      "ctl-button-name",
      "ctl-link-name",
      "ctl-html-lang",
      "ctl-focus-order",
      "ctl-input-label",
      "ctl-heading-order",
      "ctl-empty-heading",
      "ctl-iframe-title",
      "ctl-autoplay-media",
      "ctl-duplicate-id",
      "ctl-form-error-association",
      "ctl-aria-hidden-focusable",
      "ctl-aria-role",
      "ctl-aria-props",
      "ctl-aria-required-attr",
      "ctl-no-autofocus",
      "ctl-keyboard-interaction",
      "ctl-color-contrast",
      "ctl-document-title",
      "ctl-bypass",
      "ctl-landmark-one-main",
      "ctl-nested-interactive",
      "ctl-target-size",
      "ctl-meta-viewport",
      "ctl-list-structure",
      "ctl-autocomplete-valid",
      "ctl-table-headers",
      "ctl-page-heading",
      "ctl-content-region",
      "ctl-label-in-name",
      "ctl-lang-parts",
      "ctl-aria-roledescription",
      "ctl-presentation-role",
      "ctl-no-auto-refresh",
      "ctl-no-orientation-lock",
      "ctl-pointer-gesture",
      "ctl-pointer-cancellation",
      "ctl-motion-actuation",
      "ctl-focus-context-change",
      "ctl-input-context-change",
      "ctl-sensory-characteristics",
      "ctl-image-of-text",
      "ctl-error-suggestion",
    ],
  },
];