import { wcagControls, wcagFramework } from "./controls";
import type { FrameworkPreset } from "@/adapters/types";

export type { FrameworkPreset };

/** Curated subsets of the WCAG adapter for one-click scoping. */
export const wcagPresets: FrameworkPreset[] = [
  {
    id: "preset-wcag-full",
    name: "Full WCAG 2.1",
    description: "Every machine-checkable control from WCAG 2.1",
    frameworkId: wcagFramework.id,
    controlIds: wcagControls.map((control) => control.id),
  },
  {
    id: "preset-wcag-aa",
    name: "WCAG 2.1 AA",
    description: "Core WCAG 2.1 AA success criteria",
    frameworkId: wcagFramework.id,
    controlIds: [
      "ctl-img-alt",
      "ctl-button-name",
      "ctl-link-name",
      "ctl-html-lang",
      "ctl-focus-order",
      "ctl-input-label",
      "ctl-heading-order",
      "ctl-empty-heading",
      "ctl-iframe-title",
      "ctl-autoplay-media",
      "ctl-duplicate-id",
      "ctl-form-error-association",
      "ctl-aria-hidden-focusable",
      "ctl-aria-role",
      "ctl-aria-props",
      "ctl-aria-required-attr",
      "ctl-no-autofocus",
      "ctl-keyboard-interaction",
      "ctl-color-contrast",
      "ctl-document-title",
      "ctl-bypass",
      "ctl-landmark-one-main",
      "ctl-nested-interactive",
      "ctl-target-size",
      "ctl-meta-viewport",
      "ctl-list-structure",
      "ctl-autocomplete-valid",
      "ctl-table-headers",
      "ctl-page-heading",
      "ctl-content-region",
      "ctl-label-in-name",
      "ctl-lang-parts",
      "ctl-aria-roledescription",
      "ctl-presentation-role",
      "ctl-no-auto-refresh",
      "ctl-no-orientation-lock",
    ],
  },
  {
    id: "preset-wcag-aaa",
    name: "WCAG 2.1 AAA",
    description: "Enhanced WCAG 2.1 AAA success criteria",
    frameworkId: wcagFramework.id,
    controlIds: [
      "ctl-img-alt",
      "ctl-button-name",
      "ctl-link-name",
      "ctl-html-lang",
      "ctl-focus-order",
      "ctl-input-label",
      "ctl-heading-order",
      "ctl-empty-heading",
      "ctl-iframe-title",
      "ctl-autoplay-media",
      "ctl-duplicate-id",
      "ctl-form-error-association",
      "ctl-aria-hidden-focusable",
      "ctl-aria-role",
      "ctl-aria-props",
      "ctl-aria-required-attr",
      "ctl-no-autofocus",
      "ctl-keyboard-interaction",
      "ctl-color-contrast",
      "ctl-document-title",
      "ctl-bypass",
      "ctl-landmark-one-main",
      "ctl-nested-interactive",
      "ctl-target-size",
      "ctl-meta-viewport",
      "ctl-list-structure",
      "ctl-autocomplete-valid",
      "ctl-table-headers",
      "ctl-page-heading",
      "ctl-content-region",
      "ctl-label-in-name",
      "ctl-lang-parts",
      "ctl-aria-roledescription",
      "ctl-presentation-role",
      "ctl-no-auto-refresh",
      "ctl-no-orientation-lock",
      "ctl-pointer-gesture",
      "ctl-pointer-cancellation",
      "ctl-motion-actuation",
      "ctl-focus-context-change",
      "ctl-input-context-change",
      "ctl-sensory-characteristics",
      "ctl-image-of-text",
      "ctl-error-suggestion",
    ],
  },
  {
    id: "preset-wcag-images-media",
    name: "Images & media",
    description: "Text alternatives, frames, and autoplay media.",
    frameworkId: wcagFramework.id,
    controlIds: [
      "ctl-img-alt",
      "ctl-iframe-title",
      "ctl-autoplay-media",
    ],
  },
  {
    id: "preset-wcag-forms-names",
    name: "Forms & accessible names",
    description: "Labels, buttons, links, and autocomplete purpose.",
    frameworkId: wcagFramework.id,
    controlIds: [
      "ctl-input-label",
      "ctl-button-name",
      "ctl-link-name",
      "ctl-form-error-association",
      "ctl-autocomplete-valid",
      "ctl-label-in-name",
    ],
  },
  {
    id: "preset-wcag-structure",
    name: "Page structure",
    description: "Language, headings, lists, viewport zoom, and focus order.",
    frameworkId: wcagFramework.id,
    controlIds: [
      "ctl-html-lang",
      "ctl-heading-order",
      "ctl-empty-heading",
      "ctl-focus-order",
      "ctl-duplicate-id",
      "ctl-aria-hidden-focusable",
      "ctl-list-structure",
      "ctl-meta-viewport",
      "ctl-page-heading",
      "ctl-content-region",
      "ctl-no-orientation-lock",
      "ctl-landmark-unique",
    ],
  },
  {
    id: "preset-wcag-heuristics",
    name: "Advanced heuristics",
    description:
      "Lower-confidence AST checks for pointer/keyboard parity, context changes, sensory instructions, images of text, and error suggestions. Surfaces items for human review.",
    frameworkId: wcagFramework.id,
    controlIds: [
      "ctl-pointer-gesture",
      "ctl-pointer-cancellation",
      "ctl-motion-actuation",
      "ctl-focus-context-change",
      "ctl-input-context-change",
      "ctl-sensory-characteristics",
      "ctl-image-of-text",
      "ctl-error-suggestion",
    ],
  },
];